### ISSUE TITLE
[Bug]: All test fails after upgrade from 9.0.7 to 10.x.x

### ISSUE THREAD

**Issue by rickvandermey** [thymikee/jest-preset-angular#1068]
### Version

10.0.1

### Steps to reproduce

1. clone https://github.com/rickvandermey/angular-starterkit/tree/bug/jest-preset-angular
2. run `npm ci`
3. run `npm run test:ci`

### Expected behavior

I expect all test to pass

### Actual behavior

after the upgrade from 9.0.7 to 10.0.1 all my test fail with the following message:

```
Test suite failed to run

    Cannot set base providers because it has already been called

      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.initTestEnvironment (../packages/core/testing/src/test_bed.ts:308:13)
      at Object.<anonymous> (node_modules/jest-preset-angular/setup-jest.js:1:100)
      at Object.<anonymous> (jest.setup.ts:1:1)
```

### Environment

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 7.21.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    jest: 27.2.4 => 27.2.4 


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.9
Node: 14.16.1
Package Manager: npm 7.21.0
OS: darwin x64

Angular: 12.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@nguniversal/express-engine     12.1.1
@schematics/angular             12.2.9
rxjs                            7.4.0
typescript                      4.3.5
webpack                         5.58.0
```

**Comment by rickvandermey** [comment]
Hmmm, i will remove the `@angular-builder/jest` and update the `angular.json`
Running `npx jest` directlly seems to work

**Comment by ahnpnl** [comment]
I will close this issue as running with Jest works fine. It's the issue with `@angular-builder/jest`

**Comment by robingenz** [comment]
Just in case anyone else encounters this problem: My solution was to remove the `setup-jest.ts` file, since `import 'jest-preset-angular/setup-jest';` is already executed by `@angular-builders/jest`.
