### ISSUE TITLE
[Bug]: Running jest on Angular 13 with ngcc fails with a path error to ngcc

### ISSUE THREAD

**Issue by FlorianSW** [thymikee/jest-preset-angular#1139]
### Version

v11.0.0-rc.1

### Steps to reproduce

1. Create an Angular 13 project which relies on at least one non-Ivy build dependency
2. Enable jest-angular-preset (as documented)
3. Add the ngcc-processor in the setupJest.ts (js) file:
```
import 'jest-preset-angular/ngcc-jest-processor';
```
4. Run npm test (or however you usually run tests)

### Expected behavior

The tests should run after ngcc compiled the necessary non-ivy modules.

### Actual behavior

The jest test run fails on the pre-compile step:
```
Cannot find module '@angular/compiler-cli/ngcc' from 'node_modules/jest-preset-angular/build/utils/ngcc-jest-processor.js'

    Require stack:
      node_modules/jest-preset-angular/build/utils/ngcc-jest-processor.js
      node_modules/jest-preset-angular/ngcc-jest-processor.js
      src/setupJest.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/jest-preset-angular/ngcc-jest-processor.js:1:100)
```

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.11.0 - /usr/local/bin/node
    npm: 8.1.3 - /usr/local/bin/npm
  npmPackages:
    jest: ^27.3.1 => 27.3.1
```

**Comment by FlorianSW** [comment]
nvm, should have read the documentation correctly, that the ngcc processor is only working with a js based config (not in the setupJest like I did it).
