### ISSUE TITLE
reported lines are incorrect

### ISSUE THREAD

**Issue by marcuskrahl** [thymikee/jest-preset-angular#123]
# Issue

When using the Jest preset for Angular with a new Angular CLI project failed tests in a spec file are reported with incorrect line numbers

# Repro Steps
1. `ng new <test project`
2. `npm install --saveDev jest jest-preset-angular`
3. Add a `setupJest.ts` file as demonstrated in the Readme
4. Adjust `package.json`
5. Add a failing statement to `app.component.spec.ts`
6. Run `jest`

Running jest the following output is generated:
```
FAIL  src\app\app.component.spec.ts
  AppComponent
    √ should create the app (140ms)
    × should have as title 'app' (91ms)
    √ should render title in a h1 tag (54ms)

  ● AppComponent › should have as title 'app'

    expect(received).toBeFalsy()

    Expected value to be falsy, instead received
      true

      20 |     expect(true).toBeFalsy();
      21 |   }));
    > 22 |   it('should render title in a h1 tag', async(() => {
      23 |     const fixture = TestBed.createComponent(AppComponent);
      24 |     fixture.detectChanges();
      25 |     const compiled = fixture.debugElement.nativeElement;

      at src/app/app.component.spec.ts:22:22
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
      at runInTestZone (node_modules/@angular/core/bundles/core-testing.umd.js:141:25)
      at node_modules/@angular/core/bundles/core-testing.umd.js:80:13
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length.done (node_modules/jest-zone-patch/index.js:51:29)
```

The line indicator points to an error in line 22, but the error should be in line 20

# Sample Repo

[https://github.com/marcuskrahl/angular-jest-test](https://github.com/marcuskrahl/angular-jest-test)

This issue makes it hard to use Jest with Angular together with the VS Code plugin because the plugin relies on correctly emitted error lines

**Comment by thymikee** [comment]
Have you tried latest Jest, e.g. 22.3.0? We had issues after removing "retainLines" from babel config.

**Comment by marcuskrahl** [comment]
Yes I did try it using a freshly installed version of angular and yest. The sample repo uses jest 22.3.0

This issue happens on a Windows machine by the way. I will check a Linux machine later 

Am 16. Februar 2018 16:18:21 MEZ schrieb "Michał Pierzchała" <notifications@github.com>:
>Have you tried latest Jest, e.g. 22.3.0? We had issues after removing
>"retainLines" from babel config.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thymikee/jest-preset-angular/issues/123#issuecomment-366263694

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by AhnpGit** [comment]
@thymikee I have that issue also with my work's project. I'm not sure either jest or ts-jest has issues but my guess is on ts-jest. I didn't have time to check with only jest yet

**Comment by thymikee** [comment]
Looks like it was broken from the very beginning of Jest 22. Happens in all minor versions of Jest v22 and ts-jest@21 and ts-jest@22. I've tested that against jest's master, where we revamped coverage remapping and the issue is gone.

**Comment by thymikee** [comment]
So keep an eye on Jest 22.4.0!
