### ISSUE TITLE
Can't resolve all parameters (?, ?)

### ISSUE THREAD

**Issue by aaronte** [thymikee/jest-preset-angular#154]
**Issue**

• Trying to test using `TestBed.configureTestingModule().compileComponents()`.
• Testing w/o using Angular `TestBed` and just testing using classes works. 
• Failing because of following error:
```sh
Can't resolve all parameters for AppComponent: (?, ?).      
      at syntaxError (../../../../execroot/angular/packages/compiler/src/util.ts:100:17)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver._getDependenciesMetadata (../../../../execroot/angular/packages/compiler/src/metadata_resolver.ts:959:27)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver._getTypeMetadata (../../../../execroot/angular/packages/compiler/src/metadata_resolver.ts:839:20)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (../../../../execroot/angular/packages/compiler/src/metadata_resolver.ts:380:18)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver.loadDirectiveMetadata (../../../../execroot/angular/packages/compiler/src/metadata_resolver.ts:227:11)
      at ../../../../execroot/angular/packages/compiler/src/jit/compiler.ts:135:36
          at Array.forEach (<anonymous>)
      at ../../../../execroot/angular/packages/compiler/src/jit/compiler.ts:133:65
          at Array.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._loadModules (../../../../execroot/angular/packages/compiler/src/jit/compiler.ts:130:71)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../../../../execroot/angular/packages/compiler/src/jit/compiler.ts:115:32)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsAsync (../../../../execroot/angular/packages/compiler/src/jit/compiler.ts:69:33)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsAsync (../../../../execroot/angular/packages/platform-browser-dynamic/src/compiler_factory.ts:68:27)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsAsync (../../../../execroot/packages/platform-browser-dynamic/testing/src/compiler_factory.ts:57:27)
      at TestBed.Object.<anonymous>.TestBed.compileComponents (../../../../execroot/packages/core/testing/src/test_bed.ts:335:27)
      at Function.Object.<anonymous>.TestBed.compileComponents (../../../../execroot/packages/core/testing/src/test_bed.ts:116:66)
      at packages/micro-client/src/app/app.component.spec.ts:92:9
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
      at runInTestZone (../../../../execroot/packages/core/testing/src/async_fallback.ts:115:23)
      at ../../../../execroot/packages/core/testing/src/async_fallback.ts:46:7
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:79:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length.done (node_modules/jest-zone-patch/index.js:51:29)
```

**app.component.spec.ts**
```ts
import { TestBed, async } from '@angular/core/testing';

import { AppComponent } from './app.component';
import { UserService } from './services/user.service';
import { AnimalService } from './services/animal.service';

class MockUserService {}
class MockAnimalService {}

describe('AppComponent', () => {
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            declarations: [
                AppComponent,
            ],
            providers: [
                {
                    provider: UserService,
                    useClass: MockUserService,
                },
                {
                    provider: AnimalService,
                    useClass: MockAnimalService,
                },
            ],
        }).compileComponents();
    }));

    it('should create the app', async(() => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.componentInstance;
        expect(app).toBeTruthy();
    }));
});
```

**animal.service.ts**

```ts
import { Component, OnInit } from '@angular/core';

import { UserService } from './services/user.service';
import { AnimalService } from './services/animal.service';

@Component({
    selector: 'app',
    templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
    
    constructor(private animalService: AnimalService, private userService: UserService) {
    }

    ngOnInit() {
    }
}
```

Any help is appreciated!!!

**Comment by AhnpGit** [comment]
Hi, of you are using TestBed, please take a look at example folder of this repositories. It contains example tests and example setup.

**Comment by aaronte** [comment]
@AhnpGit Hi! I've followed all the examples but none of it seems to be using DI for any of its components?

**Comment by aaronte** [comment]
My mistake. Im using `provider` instead of `provide` in setting up my `providers`. Closing this issue.
