### ISSUE TITLE
[Bug]: MsalModule does not have a module def (ɵmod property)

### ISSUE THREAD

**Issue by rafagsiqueira** [thymikee/jest-preset-angular#1658]
### Version

12.1.0

### Steps to reproduce

Any unit test which imports MsalModule:
```
TestBed.configureTestingModule({
      declarations: [ AppComponent ],
      imports: [
        MsalModule
      ]
});
```

### Expected behavior

Unit test should pass.

### Actual behavior

The following error message:
```
MsalModule does not have a module def (ɵmod property)

      18 |
      19 |   beforeEach(async() => {
    > 20 |     TestBed.configureTestingModule({
         |             ^
      21 |       declarations: [ AppComponent ],
      22 |       imports: [
      23 |         DialogModule,

      at transitiveScopesFor (node_modules/@angular/core/fesm2020/core.mjs:24882:11)
      at node_modules/@angular/core/fesm2020/core.mjs:24912:31
          at Array.forEach (<anonymous>)
      at transitiveScopesForNgModule (node_modules/@angular/core/fesm2020/core.mjs:24909:32)
      at transitiveScopesFor (node_modules/@angular/core/fesm2020/core.mjs:24849:16)
      at setScopeOnDeclaredComponents (node_modules/@angular/core/fesm2020/core.mjs:24812:30)
      at flushModuleScopingQueueAsMuchAsPossible (node_modules/@angular/core/fesm2020/core.mjs:24459:21)
      at TestBedRender3.checkGlobalCompilationFinished (node_modules/@angular/core/fesm2020/testing.mjs:26640:13)
      at TestBedRender3.configureTestingModule (node_modules/@angular/core/fesm2020/testing.mjs:26515:14)
      at Function.configureTestingModule (node_modules/@angular/core/fesm2020/testing.mjs:26363:30)
      at projects/etips-registration/src/app/app.component.spec.ts:20:13
      at node_modules/tslib/tslib.js:118:75
      at new ZoneAwarePromise (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1351:25)
      at Object.__awaiter (node_modules/tslib/tslib.js:114:16)
      at projects/etips-registration/src/app/app.component.spec.ts:19:24
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)
```
### Additional context
jest.config.js
```
globalThis.ngJest = {
  skipNgcc: true,
  tsconfig: 'tsconfig.spec.json'
};

module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: '<rootDir>/global-setup.ts',
  moduleNameMapper: {
    '^etips-utils/src/lib/(.*)$': 'etips-utils/src/lib/$1',
    '^etips-utils/(.*)$': 'etips-utils/src/lib/$1'
  },
  transform: {
    '^.+\\.(ts|html)$': 'jest-preset-angular',
    '^.+\\.js$': 'babel-jest',
  },
  modulePathIgnorePatterns: ['<rootDir>/projects/etips-utils/dist'],
  globals: {
    crypto: require('crypto')
  }
};
```

### Environment

```shell
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 3.1.0 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  npmPackages:
    jest: ^28.1.1 => 28.1.1
```

**Comment by ahnpnl** [comment]
We have example app https://github.com/thymikee/jest-preset-angular/tree/main/examples here pls put your reproduce scenario there.

**Comment by rafagsiqueira** [comment]
It actually succeeds when using the example app [example-app-v14](https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v14)! Thank you so much! I will look into adjusting my config based on the example v14.
I suspect it's related to the esm setup, since I am getting this message: 
```
ngcc-jest-processor: running ngcc
Processing legacy "View Engine" libraries:
- @azure/msal-angular [es2015/esm2015] (https://github.com/AzureAD/microsoft-authentication-library-for-js.git)
- @azure/msal-angular [main/umd] (https://github.com/AzureAD/microsoft-authentication-library-for-js.git)
```
when running the test.

**Comment by rafagsiqueira** [comment]
Quick question, how can I run an asynchronous function before or after jest-preset-angular/global-setup? Can I replace the global-setup by my own async function and then call your global setup?

**Comment by ahnpnl** [comment]
Yes you can replace with your own global setup function and invoke our global setup function

**Comment by rafagsiqueira** [comment]
Just by using this on my own global setup function?
`import 'jest-preset-angular/global-setup';`

**Comment by ahnpnl** [comment]
It would be similar to how the tests are done here https://github.com/thymikee/jest-preset-angular/blob/main/src/config/global-setup.spec.ts 

Because `global-setup` exports a default function so you need to import and then invoke it inside your function

**Comment by rafagsiqueira** [comment]
I had tried that approach but couldn't make it work:
```
import globalSetup from 'jest-preset-angular/global-setup';
...
await globalSetup();
```
results on the following error:
```TypeError: Jest: Got error running globalSetup - /Users/rafasiqueira/Work/etips/global-setup.ts, reason: (0 , global_setup_1.default) is not a function```

**Comment by ahnpnl** [comment]
Are you sure you are following Jest doc https://jestjs.io/docs/configuration#globalsetup-string to configure your own global setup?

**Comment by rafagsiqueira** [comment]
I believe I am. My custom global setup exports an async function which is successfully ran. What I wasn't able to do was running the function from jest-preset-angular/global-setup.
Using require inside the async function seems to solve the problem, although I am not sure why:
```
import { ConfidentialClientApplication, NodeAuthOptions, ClientCredentialRequest } from "@azure/msal-node";
import { SecretClient } from '@azure/keyvault-secrets';
import { DefaultAzureCredential } from '@azure/identity';

import * as fs from "fs";

async function checkCredentials() {

  const global = require('jest-preset-angular/global-setup')

  await global();
(...)
}
module.exports = checkCredentials;
```
Importing it outside the async function resulted in global being undefined.
```
import globalSetup from 'jest-preset-angular/global-setup';
import { ConfidentialClientApplication, NodeAuthOptions, ClientCredentialRequest } from "@azure/msal-node";
import { SecretClient } from '@azure/keyvault-secrets';
import { DefaultAzureCredential } from '@azure/identity';

import * as fs from "fs";

async function checkCredentials() {

  const global = require('jest-preset-angular/global-setup')

  await global();
(...)
}
module.exports = checkCredentials;
```
It would be great if jest globalSetup could accept an array of "modules which export async functions" and call them either synchronously or asynchronously, but I guess that would be something to be discussed on the Jest project.
Thank you so much for your help today. I was almost giving up on Jest and going back to Karma. You saved my whole week of work.

**Comment by ahnpnl** [comment]
it is correct that `global` is undefined. Because the function behind `'jest-preset-angular/global-setup'` is a void function https://github.com/thymikee/jest-preset-angular/blob/main/src/config/global-setup.ts. You should do like this
```
import globalSetup from 'jest-preset-angular/global-setup';
import { ConfidentialClientApplication, NodeAuthOptions, ClientCredentialRequest } from "@azure/msal-node";
import { SecretClient } from '@azure/keyvault-secrets';
import { DefaultAzureCredential } from '@azure/identity';

import * as fs from "fs";

async function checkCredentials() {
  await global();
(...)
}
module.exports = checkCredentials;
```
This is the correct way of using our `global-setup` function.

**Comment by rafagsiqueira** [comment]
I am sorry, that didn't work. The following code worked:
```
import * as globalSetup from 'jest-preset-angular/global-setup';

import { ConfidentialClientApplication, NodeAuthOptions, ClientCredentialRequest } from "@azure/msal-node";
import { SecretClient } from '@azure/keyvault-secrets';
import { DefaultAzureCredential } from '@azure/identity';

import * as fs from "fs";

async function checkCredentials() {

  await globalSetup();
(...)
```
Would you consider the following PR?
```
import { runNgccJestProcessor } from '../utils/ngcc-jest-processor';

const GlobalSetup = () => {
  const ngJestConfig = globalThis.ngJest;
  const tsconfig = ngJestConfig?.tsconfig;
  if (!ngJestConfig?.skipNgcc) {
    runNgccJestProcessor(tsconfig);
  }
}

export default GlobalSetup;
```
I believe it wouldn't disrupt the original purpose of global-setup while allowing people to import it using named or default imports.

**Comment by ahnpnl** [comment]
Yes switching to `export default` is fine, luckily that Jest already supported that way.
