### ISSUE TITLE
TypeError: test.each is not a function

### ISSUE THREAD

**Issue by marcojahn** [thymikee/jest-preset-angular#169]
Trying to use Jest 23 "test.each" error results in a TypeError.

Test
```
  test.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
    '.add(%i, %i)',
    (a, b, expected) => {
      expect(a + b).toBe(expected);
    },
  );
```

Error Message
```
 FAIL  src/app/wte/components/my-component.component.spec.ts (204 MB heap size)
  MyComponent
    ✓ should create (743ms)
    ✕ encountered a declaration exception (625ms)

  ● MyComponent › encountered a declaration exception

    TypeError: test.each is not a function

      27 |   });
      28 |
    > 29 |   test.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
         |        ^
      30 |     '.add(%i, %i)',
      31 |     (a, b, expected) => {
      32 |       expect(a + b).toBe(expected);

      at src/app/wte/components/my-component.component.spec.ts:29:8
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Suite.<anonymous> (node_modules/jest-zone-patch/index.js:39:25)
      at env.(anonymous function) (node_modules/jest-zone-patch/index.js:57:27)
      at Object.<anonymous> (src/app/wte/components/my-component.component.spec.ts:8:1)

```

Any suggestions what am I missing ?

regards

**Comment by thymikee** [comment]
Looks like you're not the only one :D https://github.com/facebook/jest/issues/6612
We're not yet officially compatible with Jest 23, because we're waiting for ts-jest to update. 
I see however that more folks try to use it and it mostly works. What needs to be updated on our side is [jest-zone-patch](https://github.com/thymikee/jest-zone-patch/blob/master/index.js), as it doesn't account for new additions to `test()` fn. Happy to accept PR with a fix :)

**Comment by marcojahn** [comment]
ok, seems to belong to https://github.com/facebook/jest/issues/6612

Installing jest-each does not resolve the problem either

**Comment by marcojahn** [comment]
@thymikee 

could it be so simple ? Or is there something I do not think about ?

Will write some tests for my code and will create a PR this evening or tomorrow

```
['xit', 'fit', 'test', 'it'].forEach(methodName => {
  const originaljestFn = env[methodName];
  env[methodName] = function(description, specDefinitions, timeout) {
    arguments[1] = wrapTestInZone(specDefinitions);
    return originaljestFn.apply(this, arguments);
  };
  if (methodName === 'test' || methodName === 'it') {
    env[methodName].only = env['fit'];
    env[methodName].skip = env['xit'];

    // modification is below this point
    // test.each(table)(name, fn)
    env[methodName].each = function (description, specDefinitions) {
      arguments[1] = wrapTestInZone(specDefinitions);
      return originaljestFn.each.apply(this, arguments);
    };
    // end of modification
  }
});
```

**Comment by thymikee** [comment]
`test.each` has different function signature: https://github.com/facebook/jest/blob/master/packages/jest-each/src/bind.js
Not sure if it matters for zone to work though.

**Comment by marcojahn** [comment]
https://github.com/thymikee/jest-zone-patch/pull/7

For other people seeking a temporary workaround until the PR is merged and/or updated until it is ok to merge below is a temporary workaround:

1) copy the file from this PR `https://github.com/thymikee/jest-zone-patch/pull/7` to your application
2) open your `setupJest.ts" file (or however you named it)
3) disable the given `import 'jest-preset-angular'
4) do the top most setup yourself

```javascript
'use strict';

import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone.js';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import './temporary.jest-zone-patch';
import { AngularSnapshotSerializer } from 'jest-preset-angular/AngularSnapshotSerializer';
import { HTMLCommentSerializer } from 'jest-preset-angular/HTMLCommentSerializer';
import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule } from '@angular/platform-browser-dynamic/testing';
import { platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
```

**Comment by kirillgroshkov** [comment]
Waiting for a fix too...

**Comment by thymikee** [comment]
Turned out I need to publish another release. Fixed in v6.0.2

**Comment by ahnpnl** [comment]
it is supported by this line https://github.com/thymikee/jest-zone-patch/blob/3c8aa04279c9c9de1edc75b4e0665c7a282ce3ba/index.js#L78 I guess ?

**Comment by NagRock** [comment]
`it.each` works but example from jest documentation:

```typescript
describe.each([[1, 1, 2], [1, 2, 3], [2, 1, 3]])(
  '.add(%i, %i)',
  (a, b, expected) => {
    test(`returns ${expected}`, () => {
      expect(a + b).toBe(expected);
    });

    test(`returned value not be greater than ${expected}`, () => {
      expect(a + b).not.toBeGreaterThan(expected);
    });

    test(`returned value not be less than ${expected}`, () => {
      expect(a + b).not.toBeLessThan(expected);
    });
  },
);
```
Fails:

```.add(2, 1) › returned value not be less than undefined

    expect(received)[.not].toBeLessThan(expected)

    Received value must be a number.
    Received:
      string: "function (a, b, expected) {
            test(\"returns \" + expected, function () {
                expect(a + b).toBe(expected);
            });
            test(\"returned value not be greater than \" + expected, function () {
                expect(a + b).not.toBeGreaterThan(expected);
            });
            test(\"returned value not be less than \" + expected, function () {
                expect(a + b).not.toBeLessThan(expected);
            });
        }undefined"

      45 |
      46 |       test(`returned value not be less than ${expected}`, () => {
    > 47 |         expect(a + b).not.toBeLessThan(expected);
         |                           ^
      48 |       });
      49 |     },
      50 |   );
```

**Comment by thymikee** [comment]
cc @JLHwung

**Comment by thymikee** [comment]
@NagRock Should be good now, you'll need to re-install to update the transitive dependency of `jest-zone-patch`

**Comment by NagRock** [comment]
Thanks. I will check it and get back with feedback.

**Comment by NagRock** [comment]
@thymikee Works like a charm 🎉 Thanks!
