### ISSUE TITLE
setting encapsulation to ViewEncapsulation.Native causes jest to fail

### ISSUE THREAD

**Issue by acb122** [thymikee/jest-preset-angular#191]
I have set encapsulation to ViewEncapsulation.Native which causes jest to fail with the below error. I would appreciate if anyone knows a fix for this.

`TypeError: hostEl.createShadowRoot is not a function

      at new ShadowDomRenderer (../packages/platform-browser/src/dom/dom_renderer.ts:263:41)
      at DomRendererFactory2.Object.<anonymous>.DomRendererFactory2.createRenderer (../packages/platform-browser/src/dom/dom_renderer.ts:87:16)
      at DebugRendererFactory2.Object.<anonymous>.DebugRendererFactory2.createRenderer (../packages/core/src/view/services.ts:661:45)
      at createComponentView (../packages/core/src/view/view.ts:221:52)
      at callWithDebugContext (../packages/core/src/view/services.ts:639:23)
      at Object.debugCreateComponentView [as createComponentView] (../packages/core/src/view/services.ts:155:10)
      at createViewNodes (../packages/core/src/view/view.ts:268:36)
      at createRootView (../packages/core/src/view/view.ts:210:3)
      at callWithDebugContext (../packages/core/src/view/services.ts:639:23)
      at Object.debugCreateRootView [as createRootView] (../packages/core/src/view/services.ts:121:10)
      at ComponentFactory_.Object.<anonymous>.ComponentFactory_.create (../packages/core/src/view/refs.ts:92:27)
      at initComponent (../../packages/core/testing/src/test_bed.ts:569:28)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:273:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:171:50)
      at TestBed.Object.<anonymous>.TestBed.createComponent (../../packages/core/testing/src/test_bed.ts:573:56)
      at Function.Object.<anonymous>.TestBed.createComponent (../../packages/core/testing/src/test_bed.ts:201:25)
      at src/app/core/component/iframe/iframe.component.spec.ts:19:23
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (node_modules/jest-zone-patch/index.js:50:27)`

**Comment by ahnpnl** [comment]
Does it happen to karma + Jasmine too ? I'm curious. Anyways, you can use override component option from TestBed to set ViewEncapsulation to default when running test. ViewEncapsulation normally affects to styling but in test environment I think it's ok to set to default.

**Comment by adover** [comment]
This worked for me:
```
    TestBed.configureTestingModule({
      imports: [...],
      providers: [...],
    }).overrideComponent(ExperimentBarComponent, {add: {encapsulation: ViewEncapsulation.Emulated}})
```

**Comment by ahnpnl** [comment]
Close as there is a workaround presented above. If you find any problems, feel free to report.
