### ISSUE TITLE
Jest only fails when run with --no-cache

### ISSUE THREAD

**Issue by Ant59** [thymikee/jest-preset-angular#197]
Jest only seems to fail when run with --no-cache option, yet passes fine without. Is there an obvious cause to this that I'm missing?

Without --no-cache (uses cache)
```
Test Suites: 90 passed, 90 total
Tests:       444 passed, 444 total
Snapshots:   0 total
Time:        27.275s, estimated 32s
Ran all test suites.
Done in 27.74s.
```

With --no-cache (or first run)
```
Summary of all failing tests
 FAIL  src/app/module1/containers/list-view/list-view.component.spec.ts (14.582s)
  ● ListMetadataComponent › should return to the first page of the table when filtering

    Uncaught (in promise): Error: expect(jest.fn()).toHaveBeenCalled()

    Expected mock function to have been called, but it was not called.
    Error: expect(jest.fn()).toHaveBeenCalled()

    Expected mock function to have been called, but it was not called.

      211 | 
      212 |     fixture.whenStable().then(() => {
    > 213 |       expect(component.paginator.firstPage).toHaveBeenCalled();
          |                                             ^
      214 |     });
      215 |   }));
      216 | });

      at src/app/module1/containers/list-view/list-view.component.spec.ts:213:45
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:125:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at node_modules/zone.js/dist/zone.js:872:34
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (node_modules/zone.js/dist/async-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:156:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:36)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
      at resolvePromise (node_modules/zone.js/dist/zone.js:814:31)
      at node_modules/zone.js/dist/zone.js:877:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (node_modules/zone.js/dist/async-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:156:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:36)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)


Test Suites: 1 failed, 89 passed, 90 total
Tests:       1 failed, 443 passed, 444 total
Snapshots:   0 total
Time:        36.639s
Ran all test suites.
```

The two tests above were run directly after each other on the same project with the following commands:

```
yarn run jest
```

```
yarn run jest --no-cache
```

**Comment by ahnpnl** [comment]
Would you please create a sample repo for this case ? We can't investigate when there are no samples

**Comment by ahnpnl** [comment]
If you still encounter the issue, feel free to leave a comment with a repo for us to reproduce the issue.
