### ISSUE TITLE
[Feature]: Support for contentChild signal functions

### ISSUE THREAD

**Issue by maxfriedmann** [thymikee/jest-preset-angular#2328]
### 🚀 Feature Proposal

I recently migrated from `@ContentChild` to `contentChild` and now jest complains: 

```typescript
@Component({ 
  template: "test",
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class TestComponent {
  protected tmpl = contentChild("hello");
}
```

Error:
```bash
 ● TestComponent › should be able to test with templates

    TypeError: Cannot read properties of undefined (reading 'tmpl')

      at Object.TestComponent_ContentQueries [as contentQueries] (../../../ng:/TestComponent.js:19:61)
      at executeContentQueries (../../../node_modules/@angular/core/fesm2022/core.mjs:10557:25)
      at createRootComponent (../../../node_modules/@angular/core/fesm2022/core.mjs:16735:5)
      at ComponentFactory.create (../../../node_modules/@angular/core/fesm2022/core.mjs:16579:25)
      at initComponent (../../../node_modules/@angular/core/fesm2022/testing.mjs:1949:51)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../../node_modules/zone.js/bundles/zone.umd.js:411:30)
      at Object.onInvoke (../../../node_modules/@angular/core/fesm2022/core.mjs:15613:33)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../../node_modules/zone.js/bundles/zone.umd.js:410:56)
      at Zone.Object.<anonymous>.Zone.run (../../../node_modules/zone.js/bundles/zone.umd.js:165:47)
      at NgZone.run (../../../node_modules/@angular/core/fesm2022/core.mjs:15464:28)
      at _TestBedImpl.createComponent (../../../node_modules/@angular/core/fesm2022/testing.mjs:1960:41)
      at Function.createComponent (../../../node_modules/@angular/core/fesm2022/testing.mjs:1753:37)
      at src/lib/components/test/test.component.spec.ts:16:23

```

### Motivation

Seems like a similar feature request like https://github.com/thymikee/jest-preset-angular/issues/2315 

Would be nice to test with components that use `contentChild()`.

**Comment by maxfriedmann** [comment]
I don't get it... Tried to reproduce it on StackBlitz and it works :) https://stackblitz.com/edit/node-djfsub

Seems like a local issue, sorry!
