### ISSUE TITLE
Unexpected tokenyntaxError: Unexpected token '??='     at wrapSafe (internal/modules/cjs/loader.js:1001:16)

### ISSUE THREAD

**Issue by Charan678578** [thymikee/jest-preset-angular#2329]
### Please do not submit this issue.

- [X] I understand

**Comment by Charan678578** [comment]
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)

**Comment by Charan678578** [comment]
Error while running npm run test

**Comment by ahnpnl** [comment]
Pls provide all information about:

- Error: stack trace
- Reproduction steps
- Example repository

**Comment by Charan678578** [comment]
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/Users/I585384/minerva/minerva-ui/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/I585384/minerva/minerva-ui/node_modules/jest-preset-angular/build/compiler/ng-jest-compiler.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! minerva-ui@0.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minerva-ui@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Charan678578** [comment]
This happened when I migrated from karma to jest and used jest configuration document for this

**Comment by ahnpnl** [comment]
You can take a look at our example app for configuration https://github.com/thymikee/jest-preset-angular/tree/main/examples

You can also try to reproduce your problem in the example app
