### ISSUE TITLE
Unexpected token export "node_modules\@angular-skyhook\core\node_modules\dnd-core\lib\index.js:1"

### ISSUE THREAD

**Issue by akankshagaur01** [thymikee/jest-preset-angular#294]
I am using react-dnd-html5-backend with @angular-skyhook/core in my application. I am getting below error while running tests.

```
location\node_modules\@angular-skyhook\core\node_modules\dnd-core\lib\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './interfaces';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at node_modules/@angular-skyhook/core/bundles/angular-skyhook-core.umd.js:2:155
      at Object.<anonymous> (node_modules/@angular-skyhook/core/bundles/angular-skyhook-core.umd.js:5:2)

```
My tsconfig.json
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": ".",
        "importHelpers": true,
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ],
        "paths": {
            "@app/*": [
                "src/app/*"
            ]
        }
    }
}
```

My tsconfig.spec.json

```
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "allowJs": true,
        "outDir": "../out-tsc/spec",
        "importHelpers": true,
        "module": "commonjs",
        "types": [
            "jest",
            "node"
        ],
        "esModuleInterop":true
    },
    "files": [
        "polyfills.ts"
    ],
    "include": [
        "*/**/*.spec.ts",
        "**/*.d.ts"
    ]
}
```

My jest.config.js

```
module.exports = {
    preset: 'jest-preset-angular',
    roots: ['src'],
    setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],
    moduleNameMapper: {
        '@app/(.*)': '<rootDir>/src/app/$1'
    },
    coverageDirectory: './coverage',
    transformIgnorePatterns: ['node_modules/(?!(jest-test))', 'node_modules/(?!@angular-skyhook)',
        'node_modules/(?!dnd-core)',
        'node_modules/(?!react-dnd-html5-backend)'
    ],
    coverageReporters: [
        'text',
        'lcov',
        'cobertura'
    ],
    reporters: ['default', 'jest-junit'],
    coverageThreshold: {
        global: {
            branches: 75,
            functions: 85,
            lines: 90,
            statements: 90
        }
    }
};
```

**Comment by wtho** [comment]
It seems the issue is that in `node_modules` there is code using `es6`-style `import` and `export`. Currently this is not valid Node.js syntax, so when jest tries to load it (and jest runs in Node.js), it does not recognize the `export` keyword.

I think the easiest way is to let the TypeScript compiler handle this. Set `allowJs` in `tsconfig.spec.json` to true and remove it from `transformIgnorepatterns`. You might have to play with these options, but it should work. The `tsc` will then turn `export` to `module.exports`.

Another option might be to play with [esm](https://nodejs.org/api/esm.html), but I have no experience with this and do not know if it would work with jest.

**Comment by ahnpnl** [comment]
Also probably transformIgnorePatterns needs to be defined

**Comment by ahnpnl** [comment]
Close as inactive. If you still have issues, feel free to open a new one

**Comment by madhanhere** [comment]
In my case 

In **jest.config.js** 

I have added 

```
transformIgnorePatterns: [
    'node_modules/(?!(react-dnd|dnd-core|react-dnd-html5-backend)/)'
  ],
  ```
  And in **tsconfig.js** 
  
  I have added ```allowJs: true```  inside compileOptions
