### ISSUE TITLE
Jest Integration with angular 8. The "id" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by anuragmca90** [thymikee/jest-preset-angular#295]
I am using the angular 8.2.0 and i am trying to configure the jest:
https://github.com/just-jeb/angular-builders/tree/master/packages/jest

But when I am running the ng test I am getting the validation error.

> Preset jest-preset-angular is invalid:
The "id" argument must be of type string. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
at validateString (internal/validators.js:125:11)
at Module.require (internal/modules/cjs/loader.js:687:3)
at require (internal/modules/cjs/helpers.js:25:18)
at setupPreset (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\normalize.js:219:14)
at normalize (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\normalize.js:544:15)
at readConfig (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\index.js:163:46)
at readConfigs (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\index.js:372:26)
at U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules@jest\core\build\cli\index.js:155:58
at Generator.next ()
at asyncGeneratorStep (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules@jest\core\build\cli\index.js:108:24)

devDependencies are: 
![Untitled](https://user-images.githubusercontent.com/6928765/62603491-a11c1480-b913-11e9-8591-6d42d36d0701.png)

> "devDependencies": {
    "@angular-builders/jest": "^8.0.4",
    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "~8.2.0",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^24.0.17",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.8.0",
    "jest-preset-angular": "^7.1.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
  "jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/setupJest.ts"
    ]
  }

**Comment by ahnpnl** [comment]
Please check your jest config. There is something wrong with your jest config. If you still experience the issue, please provide a repo to reproduce the problem.

Note that Angular 8 support is dropped in v9.0.0
