### ISSUE TITLE
Illegal state: Could not load the summary for directive AppComponent.

### ISSUE THREAD

**Issue by basickarl** [thymikee/jest-preset-angular#297]
```
karl@karl-Dell-Precision-M3800:~/dev/the-ang-way-7$ npx jest --config ./jest.config.js
loading jest.config.js file
 FAIL  tests/client/unit/app.component.test.ts
  AppComponent
    ✕ the title is 'mop' (608ms)

  ● AppComponent › the title is 'mop'

    Illegal state: Could not load the summary for directive AppComponent.

      at syntaxError (../packages/compiler/src/util.ts:100:17)
      at CompileMetadataResolver.getDirectiveSummary (../packages/compiler/src/metadata_resolver.ts:423:11)
      at JitCompiler.getComponentFactory (../packages/compiler/src/jit/compiler.ts:73:44)
      at CompilerImpl.getComponentFactory (../packages/platform-browser-dynamic/src/compiler_factory.ts:77:27)
      at TestingCompilerImpl.getComponentFactory (../../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:61:27)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:595:45)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:247:36)
      at tests/client/unit/app.component.test.ts:7:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:126:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:161:47)
      at runInTestZone (node_modules/zone.js/dist/async-test.js:234:29)
      at node_modules/zone.js/dist/async-test.js:168:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Object.testBody.length.done (node_modules/jest-preset-angular/zone-patch/index.js:53:29)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.169s
Ran all test suites.
```
./tsconfig.test.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/test",
    "types": [
      "jest"
    ]
  },
  "files": [
    "./client/polyfills.ts"
  ],
  "include": [
    "./**/*.test.ts",
    "./**/*.d.ts"
  ]
}
```
./jest.config.js
```
console.log('loading jest.config.js file');
module.exports = {
    preset: 'jest-preset-angular',
    setupFilesAfterEnv: ['<rootDir>/tests/client/jest-setup.ts'],
    globals: {
        'ts-jest': {
            tsConfig: '<rootDir>/tsconfig.test.json',
            diagnostics: false
        }
    }
};
```
./client/polyfills.ts
```
import 'zone.js/dist/zone';
```
./tests/client/jest-setup.ts
```
import 'jest-preset-angular';
```
./tests/client/unit/app.component.test.ts
```
import { TestBed, async } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from '../../../client/app/app.component';

describe('AppComponent', () => {
  test(`the title is 'mop'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('mop');
  }));
});
```

Also when I try and test the following file:
```
import { TestBed, async } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from '../../../client/app/app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'mop'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('mop');
  });

  it('should render title in a h1 tag', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('Welcome to mop!');
  });
});
```
It results in this error:
```
karl@karl-Dell-Precision-M3800:~/dev/the-ang-way-7$ npx jest --config ./jest.config.js
loading jest.config.js file
  console.error node_modules/jest-environment-jsdom-thirteen/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/karl/dev/the-ang-way-7/node_modules/jest-environment-jsdom-thirteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
        at Request.client.on.err (/home/karl/dev/the-ang-way-7/node_modules/jest-environment-jsdom-thirteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
        at Request.emit (events.js:203:15)
        at Request.onRequestError (/home/karl/dev/the-ang-way-7/node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:198:13)
        at Socket.socketErrorListener (_http_client.js:392:9)
        at Socket.emit (events.js:198:13)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:63:19) undefined

 FAIL  tests/client/unit/app.component.test.ts
  AppComponent
    ✕ should create the app (164ms)
    ✕ should have as title 'mop' (19ms)
    ✕ should render title in a h1 tag (17ms)

  ● AppComponent › should create the app

    Uncaught (in promise): Failed to load app.component.html

      at resolvePromise (node_modules/zone.js/dist/zone.js:831:31)
      at resolvePromise (node_modules/zone.js/dist/zone.js:788:17)
      at node_modules/zone.js/dist/zone.js:892:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:423:31)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (node_modules/zone.js/dist/async-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:157:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:422:60)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:195:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:601:35)
      at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (node_modules/zone.js/dist/zone.js:502:21)
      at invokeTask (node_modules/zone.js/dist/zone.js:1744:14)
      at XMLHttpRequest.globalZoneAwareCallback (node_modules/zone.js/dist/zone.js:1770:17)
      at Request.onRequestError (node_modules/request/request.js:881:8)

  ● AppComponent › should create the app

    This test module uses the component AppComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:395:17)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:594:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:247:36)
      at tests/client/unit/app.component.test.ts:18:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Object.testBody.length (node_modules/jest-preset-angular/zone-patch/index.js:52:27)

  ● AppComponent › should have as title 'mop'

    This test module uses the component AppComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:395:17)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:594:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:247:36)
      at tests/client/unit/app.component.test.ts:24:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Object.testBody.length (node_modules/jest-preset-angular/zone-patch/index.js:52:27)

  ● AppComponent › should render title in a h1 tag

    This test module uses the component AppComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

      at TestBedViewEngine._initIfNeeded (../../packages/core/testing/src/test_bed.ts:395:17)
      at TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:594:10)
      at Function.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:247:36)
      at tests/client/unit/app.component.test.ts:30:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at Object.testBody.length (node_modules/jest-preset-angular/zone-patch/index.js:52:27)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        3.059s
Ran all test suites.
  console.error node_modules/zone.js/dist/zone.js:682
    Unhandled Promise rejection: Failed to load app.component.html ; Zone: ProxyZone ; Task: Promise.then ; Value: Failed to load app.component.html undefined

  console.error node_modules/zone.js/dist/zone.js:682
    Unhandled Promise rejection: Failed to load app.component.html ; Zone: ProxyZone ; Task: Promise.then ; Value: Failed to load app.component.html undefined
```
./package.json
```
{
  "name": "mop",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-builders/jest": "^7.4.4",
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.9",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^24.0.17",
    "@types/node": "~8.9.4",
    "@typescript-eslint/eslint-plugin": "^1.13.0",
    "@typescript-eslint/parser": "^1.13.0",
    "codelyzer": "~4.5.0",
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-angular": "^4.0.1",
    "eslint-plugin-jest": "^22.14.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.8.0",
    "jest-preset-angular": "^7.1.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "prettier": "^1.18.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

**Comment by wtho** [comment]
Note, that when you override `glbals.ts-jest`, you are actually overriding the whole object. Make sure you copy the original values from inside `globals.ts-jest` in your jest config

**Comment by basickarl** [comment]
@wtho Ah yes I noticed! I wrote in this thread what the issue is basically, so I understand what is happening now: https://github.com/thymikee/jest-preset-angular/issues/286#issuecomment-519050423

**Comment by kerolos-sss** [comment]
just had the same issue
