### ISSUE TITLE
Cannot read property 'getComponentFromError' of null

### ISSUE THREAD

**Issue by julienbourgainpro** [thymikee/jest-preset-angular#358]
After upgrading from v8.0.0 to v8.1.0 on my project i'm getting this error an error in ng-bullet : 
```
TypeError: Cannot read property 'fail' of undefined

      at ../../node_modules/ng-bullet/bundles/ng:/ng-bullet/src/testing.ts:26:36
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:396:30)
      at ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:395:36)
      at Zone.run (../../node_modules/zone.js/dist/zone.js:153:47)
```

and without ng-bullet webstorm say me this error : 
```
TypeError: Cannot read property 'getComponentFromError' of null

    at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (/home/julien/packages/core/testing/src/test_bed.ts:387:46)
    at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.inject (/home/julien/packages/core/testing/src/test_bed.ts:474:10)
    at Function.Object.<anonymous>.TestBedViewEngine.inject (/home/julien/packages/core/testing/src/test_bed.ts:223:36)
```

Angular : 9.0.6
Angular cli : 9.0.6
nrwl/nx : 9.1.0

To reproduce the problem.

```
yarn create nx-workspace -> choose angular project
ng update --all --force
ng add ng-bullet
```

```
some.service.ts

@Injectable({providedIn: 'root'})
export class TagService {
}
```
Reproduce the ng-bullet error :
```
some.service.spec.ts
import { configureTestSuite } from 'ng-bullet';

describe('TagService', () => {
  let tagService: TagService;

  configureTestSuite(() => {
    TestBed.configureTestingModule({
      providers: [
        TagService
      ]
    });
    tagService = TestBed.inject(TagService);
  });

  it(`should return same array if no diff`, () => {
    expect(true).toBe(true);
  });
});
```

To have the webstorm error, Replace `configureTestSuite` by `beforeEach` and run the test in any jetbrains product that integrate jest

**Comment by ahnpnl** [comment]
hi would you please provide a repo to reproduce the issue ?

**Comment by ahnpnl** [comment]
hi, can you please provide the content of `configureTestSuite` ?

**Comment by julienbourgainpro** [comment]
sorry ! i have updated the issue, it's a function from ng-bullet

```
import { configureTestSuite } from 'ng-bullet';
```

**Comment by julienbourgainpro** [comment]
ng-bullet works well with angular v9 nrwl 9 and jest 25 and jest-preset-angular 8.0.0 but not with jest-preset-angular 8.1.0

**Comment by julienbourgainpro** [comment]
v8.1.1 fix that ! thank you !

**Comment by ahnpnl** [comment]
oh so it seems to be related to changes for zone-patch in 8.1.0 👍
