### ISSUE TITLE
Template parse errors:  Can't bind to 'routerLink' since it isn't a known property of 'a'.

### ISSUE THREAD

**Issue by anandjaisy** [thymikee/jest-preset-angular#492]
## 🐛 Bug Report

In app.module I have added the 

```
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
})

export class AppRoutingModule { }
```
## Error log:
Template parse errors:
    Can't bind to 'routerLink' since it isn't a known property of 'a'. ("

        <div class="row">
            <a [ERROR ->][routerLink]="['/complete-profile']" routerLinkActive="router-link-active" class="btn btn-block notCo"): ng:///DynamicTestModule/MyAccountComponent.html@76:11
    Can't bind to 'routerLink' since it isn't a known property of 'a'. ("

        <div class="row">
            <a [ERROR ->][routerLink]="['/complete-profile']" routerLinkActive="router-link-active" class="btn btn-block compl"): ng:///DynamicTestModule/MyAccountComponent.html@82:11

      at syntaxError (../packages/compiler/src/util.ts:108:17)
      at TemplateParser.parse (../packages/compiler/src/template_parser/template_parser.ts:108:13)
      at JitCompiler._parseTemplate (../packages/compiler/src/jit/compiler.ts:300:33)
      at JitCompiler._compileTemplate (../packages/compiler/src/jit/compiler.ts:279:14)
      at ../packages/compiler/src/jit/compiler.ts:208:42
          at Set.forEach (<anonymous>)
      at JitCompiler._compileComponents (../packages/compiler/src/jit/compiler.ts:208:15)
      at ../packages/compiler/src/jit/compiler.ts:119:12
      at Object.then (../packages/compiler/src/util.ts:96:52)
      at JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:117:22)
      at JitCompiler.compileModuleAndAllComponentsAsync (../packages/compiler/src/jit/compiler.ts:69:33)
      at CompilerImpl.compileModuleAndAllComponentsAsync (../packages/platform-browser-dynamic/src/compiler_factory.ts:69:27)
      at TestingCompilerImpl.compileModuleAndAllComponentsAsync (../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:59:27)
      at TestBedViewEngine.compileComponents (../packages/core/testing/src/test_bed.ts:375:27)
      at Function.TestBedViewEngine.compileComponents (../packages/core/testing/src/test_bed.ts:159:25)
      at src/app/pages/my-account/my-account.component.spec.ts:13:6
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:102:47)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:114:43)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.runGuarded (node_modules/zone.js/dist/zone.js:154:51)
      at runInTestZone (node_modules/zone.js/dist/async-test.js:224:33)
      at node_modules/zone.js/dist/async-test.js:162:21
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.run (node_modules/zone.js/dist/zone.js:143:47)

```
```

## envinfo

```
System:
    OS:Mac os Catalina

Npm packages:
   "jest": "^26.4.2",
    "jest-preset-angular": "^8.3.1",
    typescript: 4
```

**Comment by ahnpnl** [comment]
Did you import `RouterTestingModule` into your `TestBed` ?
