### ISSUE TITLE
[Discussion]Support jest.useFakeTimers and fakeAsync()

### ISSUE THREAD

**Issue by JiaLiPassion** [thymikee/jest-preset-angular#520]
I created a PR in the angular repo https://github.com/angular/angular/pull/39016 to support integration between `fake timer APIs` of jest and `fakeAsync()`.

Any feedback is appreciate!

--------------------------------- 

After enable this feature, calling `jest.useFakeTimers()` will make all test
run into `fakeAsync()` automatically.

```
beforeEach(() => {
    jest.useFakeTimers('modern');
  });
  afterEach(() => {
    jest.useRealTimers();
  });

  test('should run into fakeAsync() automatically', () => {
    const fakeAsyncZoneSpec = Zone.current.get('FakeAsyncTestZoneSpec');
    expect(fakeAsyncZoneSpec).toBeTruthy();
  });
```

Also there are mappings between `jest` and `zone` APIs.

- `jest.runAllTicks()` will call `flushMicrotasks()`.
- `jest.runAllTimers()` will call `flush()`.
- `jest.advanceTimersByTime()` will call `tick()`
- `jest.runOnlyPendingTimers()` will call `flushOnlyPendingTimers()`
- `jest.advanceTimersToNextTimer()` will call `tickToNext()`
- `jest.clearAllTimers()` will call `removeAllTimers()`
- `jest.getTimerCount()` will call `getTimerCount()`

For detail usage, please refer to the test file 

https://github.com/angular/angular/pull/39016/files#diff-53fe8d9816dc08e106333ff822445d7fR103-R413

**Comment by ahnpnl** [comment]
I left a comment for that PR. In general, `README` here should be updated later related to that PR.

**Comment by Wykks** [comment]
This solve my issues with fakeAsync and rxjs. Thanks!

**Comment by johncrim** [comment]
I'm having issues with `fakeAsync(async () => { ...`, I receive errors after the first `await` in the async function:

```
    Expected to be running in 'ProxyZone', but it was not found.

      at Function.Object.<anonymous>.ProxyZoneSpec.assertPresent (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3660:23)
      at Object.fakeAsyncFn (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:5481:51)
```

@JiaLiPassion (aka Mr zone.js :) ), do you know if this PR fixes such issues?

**Comment by markusmo** [comment]
I saw that this is already merged with Angular. But my issue is, that the example test provided in this thread does not work for me.

could it be reagarding my `jest.config.js`:

``` javascript
module.exports = {
    extensionsToTreatAsEsm: ['.ts'],
    globals: {
        'ts-jest': {
            useESM: true,
            tsconfig: '<rootDir>/src/tsconfig.spec.json',
            stringifyContentPathRegex: '\\.(html|svg)$',
        },
    },
    moduleFileExtensions: ['ts', 'html', 'js', 'json', 'mjs'],
    moduleNameMapper: {
        '@shared/(.*)': '<rootDir>/src/app/shared/$1',
    },
    transform: {
        '^.+\\.(ts|js|mjs|html|svg)$': 'jest-preset-angular',
    },
    testEnvironment: 'jsdom',
    setupFilesAfterEnv: ['<rootDir>/setup-jest.ts', 'jest-extended/all', 'jest-marbles'],
    reporters: ['jest-spec-reporter'],
    transformIgnorePatterns: [`<rootDir>/node_modules/(?!.*\\.mjs$|${['@angular', '@ngrx', 'd3'].join('|')})`],
};
```

**Comment by dedalusMohantyMa** [comment]
any updates on this?

**Comment by johncrim** [comment]
I have tried this as well, and I'm pretty sure it doesn't work any more. Or at least, it doesn't work for ESM tests. You could try switching to CJS/non ESM mode and see if it works in that scenario with latest dependencies. Or you could just add `fakeAsync()` to your test methods.
