### ISSUE TITLE
Error when using "es2015" as the module type for typescript

### ISSUE THREAD

**Issue by jusefb** [thymikee/jest-preset-angular#55]
I am getting the following error if I use "es2015" as the module type in typescript compiler options

```
   setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install();import "jest-preset-angular";

           ^^^^^^
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules\jest-runtime\build\transform.js:321:12)
      at handle (node_modules\worker-farm\lib\child\index.js:41:8)
      at process.<anonymous> (node_modules\worker-farm\lib\child\index.js:47:3)
      at emitTwo (events.js:106:13)
```

All works fine if module is set to "commonjs"

**Comment by thymikee** [comment]
You need to define separate tsconfig for tests and use `commonjs` there. See how it's done in example: https://github.com/thymikee/jest-preset-angular/blob/master/example/src/tsconfig.spec.json
