### ISSUE TITLE
Preset jest-preset-angular is invalid

### ISSUE THREAD

**Issue by C0ZEN** [thymikee/jest-preset-angular#571]
## 🐛 Bug Report

I just wanted to run a test inside WebStorm.
It seems that there is a missing configuration somewhere.
The tests are fine when running with jest as an npm script.

Do you have any clue?

## Expected behavior

No error and the tests run.

## Link to repo (highly encouraged)

Private repo, sorry.

jest.conf.js

```
module.exports = {
    preset: 'jest-preset-angular',
    setupFilesAfterEnv: ['<rootDir>/one/src/test/javascript/jest.ts'],
    coverageDirectory: '<rootDir>/one/build/test-results/',
    globals: {
        'ts-jest': {
            tsConfig: 'tsconfig.json',
            stringifyContentPathRegex: '\\.html$',
            diagnostics: false,
            astTransformers: [require.resolve('jest-preset-angular/InlineHtmlStripStylesTransformer')]
        }
    },
    coveragePathIgnorePatterns: ['<rootDir>/one/src/test/javascript'],
    moduleNameMapper: {
        '@one/(.*)': '<rootDir>/one/src/$1',
        '@library/(.*)': '<rootDir>/library/$1',
        'core-js/es7/reflect': '<rootDir>/node_modules/core-js/proposals/reflect-metadata',
        'core-js/es6/*': '<rootDir>/node_modules/core-js/es'
    },
    reporters: ['default', ['jest-junit', { output: './build/test-results/TESTS-results-jest.xml' }]],
    testResultsProcessor: 'jest-sonar-reporter',
    transformIgnorePatterns: ['node_modules/(?!@angular/common/locales)'],
    testMatch: ['<rootDir>/one/src/app/**/@(*.)@(spec.ts)', '<rootDir>/library/**/@(*.)@(spec.ts)'],
    testPathIgnorePatterns: ['<rootDir>/one/src/test/*'],
    rootDir: '../../../../',
    testURL: 'http://localhost/'
};
```

## Error log:

```
Validation Error:

  Preset jest-preset-angular is invalid:

  The "id" argument must be of type string. Received type object
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:687:3)
    at require (internal/modules/cjs/helpers.js:25:18)
    at setupPreset (/Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/jest-config/build/normalize.js:230:14)
    at normalize (/Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/jest-config/build/normalize.js:554:15)
    at readConfig (/Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/jest-config/build/index.js:163:46)
    at readConfigs (/Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/jest-config/build/index.js:373:26)
    at /Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/@jest/core/build/cli/index.js:155:58
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/qima/Documents/github/qima/qima-platform/frontend/node_modules/@jest/core/build/cli/index.js:108:24)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html


Process finished with exit code 1
```

## envinfo

```
System:
    OS:

Npm packages:
    jest: 24.8.0
    jest-preset-angular: jest-preset-angular
    typescript: typescript
```

**Comment by C0ZEN** [comment]
Usually, everything works fine with WebStorm.
I just figured out that the project I am working on is not configured like it should be.
WebStorm try to run `ng test` but the tests in my case should be run with `jest`.
So this is not an issue with this repository, this is only related to WebStorm test runner configuration.
