### ISSUE TITLE
Can't define directives in .spec file

### ISSUE THREAD

**Issue by johncrim** [thymikee/jest-preset-angular#752]
## 🐛 Bug Report

When I define + declare an Angular directive in a test file, it doesn't work with Jest 27 and jest-preset-angular@9.0.0-next.6 . The exact same test works in karma.

```ts
import { Component, Directive, HostListener } from '@angular/core';
import { TestBed } from '@angular/core/testing';

/** A directive to prevent clicks from bubbling up to DOM ancestors. */
@Directive({
  selector: '[test-block-click-bubble]'
})
export class BlockClickBubbleDirective {

  @HostListener('click', ['$event'])
  _onClick(event: MouseEvent) {
    event.cancelBubble = true;
  }
}

@Component({
  selector: 'test-host',
  template: `
  <div (click)="outerClick">
    <button [test-block-click-bubble] (click)="innerClick()">Click me</button>
  </div>`
})
export class TestHostComponent {

  outerClick() { }
  innerclick() { }
}


describe('A directive can be declared in the test file', () => {

  it('and used in a test', () => {
    TestBed.configureTestingModule({
      declarations: [BlockClickBubbleDirective, TestHostComponent]
    });
    const fixture = TestBed.createComponent(TestHostComponent);

    const directive = fixture.debugElement.children[0].children[0].injector.get(BlockClickBubbleDirective);
    expect(directive).toBeTruthy();
  })

});
```

## Error log:

```
Template parse errors:
    Can't bind to 'test-block-click-bubble' since it isn't a known property of 'button'. ("
      <div (click)="outerClick">
        <button [ERROR ->][test-block-click-bubble] (click)="innerClick()">Click me</button>
      </div>"): ng:///DynamicTestModule/TestHostComponent.html@2:12

      at syntaxError (../packages/compiler/src/util.ts:108:17)
      at TemplateParser.Object.<anonymous>.TemplateParser.parse (../packages/compiler/src/template_parser/template_parser.ts:108:13)
      at JitCompiler.Object.<anonymous>.JitCompiler._parseTemplate (../packages/compiler/src/jit/compiler.ts:300:33)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileTemplate (../packages/compiler/src/jit/compiler.ts:279:14)
      at ../packages/compiler/src/jit/compiler.ts:208:42
          at Set.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileComponents (../packages/compiler/src/jit/compiler.ts:208:15)
      at ../packages/compiler/src/jit/compiler.ts:119:12
      at Object.then (../packages/compiler/src/util.ts:96:52)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:117:22)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsSync (../packages/compiler/src/jit/compiler.ts:65:38)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsSync (../packages/platform-browser-dynamic/src/compiler_factory.ts:61:35)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsSync (../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:54:27)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine._initIfNeeded (../packages/core/testing/src/test_bed.ts:389:28)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.createComponent (../packages/core/testing/src/test_bed.ts:599:10)
      at Function.Object.<anonymous>.TestBedViewEngine.createComponent (../packages/core/testing/src/test_bed.ts:245:36)
      at test-cases/inline-directive/inline-directive.spec.ts:36:29
```

## To Reproduce

```
git clone git@github.com:johncrim/repro-ivy-jest-preset-angular.git
git checkout bug/inline-directive

yarn
yarn test
```

Note that the identical karma test succeeds:

```
yarn karma:single
```

## Expected behavior

The directive should be compiled in the test, consistent with karma. It's interesting that the component (also declared inline) seems to be compiled.

## Link to repo

https://github.com/johncrim/repro-ivy-jest-preset-angular/tree/bug/inline-directive

Note: This is the `bug/inline-directive` branch - other branches have other test cases.

## envinfo

```
System:
    OS: Windows

Npm packages:
    jest: 27.0.0-next.2
    jest-preset-angular: 9.0.0-next.6
    typescript: 4.0.5
```

**Comment by ahnpnl** [comment]
This is because `ɵivyEnabled` is false with Jest while with Karma, it is true.
```
import { ɵivyEnabled }  from '@angular/core'

console.log(ɵivyEnabled);
```

This is probably because Jest loads the wrong module (the module which has not been processed by `ngcc`) into VM context to execute tests.

**Comment by johnc-ftl** [comment]
You're right! Thank you - I'm sorry for wasting your time with this.

I'd tried commenting out the `require('jest-preset-angular/ngcc-jest-processor');` b/c I noticed you'd [removed it in the most recent tests](https://github.com/thymikee/jest-preset-angular/pull/723/commits/604e6acba903714fc9932d5555c6d80cc057fe28). My thinking was that it probably wasn't needed for ESM, but you probably removed it for another reason; now that we know that everything is still UMD this makes sense.

**Comment by johncrim** [comment]
You're right! Thank you - I'm sorry for wasting your time with this.

I'd tried commenting out the `require('jest-preset-angular/ngcc-jest-processor');` b/c I noticed you'd [removed it in the most recent tests](https://github.com/thymikee/jest-preset-angular/pull/723/commits/604e6acba903714fc9932d5555c6d80cc057fe28). My thinking was that it probably wasn't needed for ESM, but you probably removed it for another reason; now that we know that everything is still UMD this makes sense.

**Comment by johncrim** [comment]
Closing: not a bug.
