### ISSUE TITLE
Error with ElementRef angular in the constructor, jest failed

### ISSUE THREAD

**Issue by mpuertao** [thymikee/jest-preset-angular#774]
## I have an error when I run the unit tests with Jest, I have component for an application in Angular, when I have in the constructor 'ElementRef', it throws the following error:

```
Incrementador Component › should create

Can't resolve all parameters for IncrementadorComponent: (?).

  at syntaxError (../packages/compiler/src/util.ts:108:17)
      at Array.forEach (<anonymous>)
      at Array.forEach (<anonymous>)
  at src/app/recovered/components/incrementador/incrementador.component.spec.ts:28:8
  at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
  at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)     
  at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
  at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
```

### IncrementadorComponent.ts

```js
import { Component, ElementRef, EventEmitter, Input, OnInit, Output, ViewChild } from '@angular/core';

@Component({
  selector: 'app-incrementador',
  templateUrl: './incrementador.component.html',
  styleUrls: ['./incrementador.component.scss']
})
export class IncrementadorComponent implements OnInit {

  @ViewChild('txtProgress') txtProgress: ElementRef;

  @Input('nombre') leyenda: string = 'Leyenda';
  @Input() progreso: number = 50;

  @Output('actualizaValor') cambioValor: EventEmitter<number> = new EventEmitter();

  constructor( private elementRef: ElementRef) { }
  // constructor( ) { }

  ngOnInit() { }

  onChanges( newValue: number ) {

    if ( newValue >= 100 ) {
      this.progreso = 100;
    }else if ( newValue <= 0 ) {
      this.progreso = 0;
    }else {
      this.progreso = newValue;
    }
    this.txtProgress.nativeElement.value = this.progreso;
    this.cambioValor.emit( this.progreso );
  }
```

### IncrementadorComponent.spec.ts

```js
import { ComponentFixture, inject, TestBed } from '@angular/core/testing';

import { IncrementadorComponent } from './incrementador.component';
import { FormsModule } from '@angular/forms';
import { By } from '@angular/platform-browser';
import { ElementRef, NO_ERRORS_SCHEMA } from '@angular/core';

export class MockElementRef extends ElementRef {
  constructor() { super(undefined); }
}


describe('Incrementador Component', () => {
  let component: IncrementadorComponent;
  let fixture: ComponentFixture<IncrementadorComponent>;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ IncrementadorComponent ],
      imports: [ FormsModule ],
      providers: [
        {
          provide: ElementRef,
          useClass: MockElementRef
        }
      ],
      schemas: [NO_ERRORS_SCHEMA]
    }).compileComponents();
    fixture = TestBed.createComponent(IncrementadorComponent);
    component = fixture.componentInstance;
  });

  test('should create', () => {
    expect(component).toBeTruthy();
  });
```

## Links help

[RepoGithub with the error](https://github.com/mpuertao/recovered-angular-advanced-jest)

[Issue Stackoverflow](https://stackoverflow.com/questions/66017614/error-with-elementref-angular-unit-test-with-jest)

## Observations

It should be mentioned that this does not happen with Jasmine-Karma. It only happens with Jest

**Comment by ahnpnl** [comment]
Hi, here are 2 things to solve your issue:

- Always run `ngcc` before running tests. This is required so that Angular uses the correct Ivy compiler.
- Set `emitDecoratorMetadata: true` in your `tsconfig.spec.json`.

I hope this helps.

**Comment by mpuertao** [comment]
@ahnpnl  very very thanks. Solutioned. You are the best
