### ISSUE TITLE
Create a FAQ for issues and solutions which can appears

### ISSUE THREAD

**Issue by thekip** [thymikee/jest-preset-angular#79]
I think this not a secret that "Angular + Jest" isn't a popular solution. So it's quite hard to find any information in the internet if you face any problems. 
I have a quite big project, (about 30mb in mono-repo) and while migrating to Jest I faced lot of issues which not described anywhere in the internet.

So my proposal, we can create a Wiki page on this github and start gather issues with solutions. To make use of Jest + Angular delightful and painless.

I can start from some: 

1. Q: ` ReferenceError: CSS is not defined` when testing components which used Material Design lib.

    A: Material Design library has a special check whether it run in browser environment or not. This check fails in `jsdom`, environment, because it's emulate browser, but not for all cases. 

add this to `setup-jest.ts`
 ```typescript
Object.defineProperty(window, 'CSS', {value: () => ({})});
 ```

2. Q:  `Could not find Angular Material core theme..` or `Could not find HammerJS` when testing components which used Material Design lib.

   A: There few possible solutions, but most bulletproof: 

add this to `setup-jest.ts`

 ```typescript
const WARN_SUPPRESSING_PATTERNS = [
 /Could not find Angular Material core theme/,
 /Could not find HammerJS/,
];

const warn = console.warn;

Object.defineProperty(console, 'warn', {
  value: (...params: string[]) => {
    if (!WARN_SUPPRESSING_PATTERNS.some((pattern) => pattern.test(params[0]))) {
      warn(...params);
    }
  }
});
```
3: Q: When run with coverage get this errors
> No file coverage available for: c:\projects\meteoguard\src\app\tasks\shared\index.ts
>  at CoverageMap.fileCoverageFor (node_modules/istanbul-lib-coverage/lib/coverage-map.js:96:15)

A: this errors appears only for index.ts files which has only import/export statements,actually I don't know why it happens (may be typescript compilation output is empty for this files), but as a workaround you can just add this `index.ts` files to coverage ignore pattern. Even more, this `index.ts` files don't have any value for coverage

`package.json`
```json
 "jest": {
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "index.ts"
    ],
  },
```

4. Q: "Syntax Error: Invalid or unexpected token" with absolutely unhelpful stack trace. 

A: Probably there is a require of file type which is not supported by Jest itself. For instance "png".
   Follow jest documentation: https://facebook.github.io/jest/docs/en/webpack.html#content

**Comment by thymikee** [comment]
Awesome you share this, thank you! There is Troubleshooting section on the Readme, where we can add extra feedback information you provided. 
If you have any ideas on how to make it discoverable, please post it here.

**Comment by thekip** [comment]
Probably we can create a Wiki for this project, and store all information there.  I think put it into readme not a good idea. 

The main thing, that this wiki page should be well prepared for google, that other developers may just copy/paste error message and find a solution.

**Comment by thekip** [comment]
in additional to first post

5.  Using '"target": "es6"' in jest setup is not currently supported by Angular JIT compiler. 

>  TypeError: Cannot convert undefined or null to object
>         at Function.getPrototypeOf (<anonymous>)
> 
>    at getParentCtor (node_modules/@angular/core/bundles/core.umd.js:1825:47)

Issue for tracking https://github.com/angular/angular/issues/15127

**Comment by damoonrashidi** [comment]
### Could not find Angular Material core theme

Full error message:

```
console.warn node_modules/@angular/material/bundles/material.umd.js:191
      Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming
```

### Solution
A possible fix is to trick angular material into thinking that the core theme is loaded by adding a selector to the JSDOM page in your `setupJest.ts` file

```typescript
declare var global: any;
const style = global.document.createElement('style');
style.innerHTML = `
  .mat-theme-loaded-marker {
    display: none;
  }
`;
global.document.head.appendChild(style);
```

This is an ugly workaround and will break if future versions of angular material do theme detection differently.

**Comment by sebald** [comment]
Not an Angular developer, but rather node + TS. Still @thekip saved me a lot of headache with his 3. tip! 😍 Just here to say thank you!

**Comment by thekip** [comment]
Thanks for warm words. Add couple thinks which figured out after updating to Angular 5 and latest material.

Q:  While testing components which used Material Design lib, you receive an error 

>   TypeError: Cannot read property 'bind' of undefined
>      at new MediaMatcher (node_modules/@angular/cdk/bundles/cdk/layout.es5.js:36:30)


A: Material Design library uses `matchMedia` browser api, wich is not presented in JsDom we need mock it.

add this to `setup-jest.ts`
 ```typescript
Object.defineProperty(window, 'matchMedia', { value: () => (
  {
    matches : false,
    addListener: () => { },
    removeListener: () => { },
  }
) });
 ```

Q: While testing components with animation in Angular 5 you receive an error: 

>The animation trigger "X" has failed to build due to the following errors:
>    - The provided animation property "transform" is not a supported CSS property for animations

```typescript
Object.defineProperty(document.body.style, 'transform', {
  value: () =>
    ({
      enumerable: true,
      configurable: true,
    }),
});
```

**Comment by bhanna1693** [comment]
The above solution no longer works (at least not for me)

**Comment by bdimir** [comment]
in you test you can set in providers this:
```
 {
    provide: MATERIAL_SANITY_CHECKS, 
    useValue: false
 }
```

**Comment by joergplewe** [comment]
Hi all!

I'm far from being a build/test expert, so I run into an issue with testing code using a WebWorker created with the `ng generate web-worker` CLI tool.

Running the test gives me 

```
src/app/mydata.service.ts:147:49 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.

            new URL("./mydata.service.worker", import.meta.url)
```

I tried my best to make my way thru the docs - without success. Can somebody give me a hand?

**Comment by ahnpnl** [comment]
import meta is an ESM feature which doesn’t work with default NodeJs commonjs mode. You need to run Jest in ESM mode.

you can check our documentation how to use ESM mode with Jest.

**Comment by joergplewe** [comment]
Wow ... that was quick. I tried the following w/o success. Something more to do?

```
// require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
  // preset: "jest-preset-angular",
  preset: "jest-preset-angular/presets/defaults-esm",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  setupFiles: ["jest-canvas-mock", "jest-webgl-canvas-mock"],
  moduleNameMapper: {
    "~/(.*)": "<rootDir>/src/$1",
  },
};
```

**Comment by ahnpnl** [comment]
Only make sure you run Jest with node esm flag, run ngcc (or use our ngcc script), set tsconfig to use module ESNext. You can also check our `examples` folder where we have ESM setup.

**Comment by joergplewe** [comment]
Thank you so far ... I cannot find a difference. Using `--experimental-vm-modules` fails at a different place.
I will try to create a WebWorker on an example project and see wether it works.

**Comment by viceice** [comment]
Having trouble using `ngcc-jest-processor`.

If i run `ngcc` after install , all jest esm tests are working fine, but when only using `ngcc-jest-processor` import, most tests fail since `tslib@2.3.1`

```
Syntax error reading regular expression.
  at @:2:108
  at ../../@:2:108
  at regularExpression (../../node_modules/cjs-module-lexer/lexer.js:1289:9)
  at parseSource (../../node_modules/cjs-module-lexer/lexer.js:228:13)
  at parseCJS (../../node_modules/cjs-module-lexer/lexer.js:43:5)

SyntaxError: The requested module '@angular/core' does not provide an export named 'Pipe'
  at Runtime.linkAndEvaluateModule (../../node_modules/jest-runtime/build/index.js:759:5)
  
SyntaxError: The requested module 'rxjs/operators' does not provide an export named 'map'
  at Runtime.linkAndEvaluateModule (../../node_modules/jest-runtime/build/index.js:759:5)
```

**Comment by viceice** [comment]
yes, cleared local jest cache seems to fix my local tests, but having issues on ci. it's running inside ephemeral docker containers.

Only the workspace is held but there is a git clean before any other commands. also currently no yarn cache involved. very strange 🤔

**Comment by ahnpnl** [comment]
The script is optional to use anyways :) Its purpose was to remind others not to “forget”to run `ngcc` before running Jest.

**Comment by viceice** [comment]
it's getting more strange. running it on ci fails with same error. when i then run the same docker image and jest command, it succeeds as itdoes locally. 

BTW: I'm using a [nrwl nx](https://nx.dev/) workspace

**Comment by ahnpnl** [comment]
I think `nx` has a cache on test which somehow takes over or does something with Jest cache.

**Comment by viceice** [comment]
i think it's not an nx issue, as i'm running jest directly.

I got it back working. I exclude the `tslib` `moduleNameMapper` and set `importHelpers=false`

**Comment by ahnpnl** [comment]
Seem like tslib has changed something which makes the `moduleNameMapper` in the preset not correct anymore. Thanks for the information 🙏

**Comment by viceice** [comment]
This is the tslib diff from v2.3.0 to v2.3.1. I'm not sure how this small change can cause those big issues 🤔 

https://app.renovatebot.com/package-diff?name=tslib&from=2.3.0&to=2.3.1

**Comment by ahnpnl** [comment]
I just corrected ESM tests in `examples` of this repo but couldn’t see the issue like yours, see https://github.com/thymikee/jest-preset-angular/actions/runs/1257005889 Our examples don’t have `nx`

**Comment by Bjeaurn** [comment]
> in you test you can set in providers this:
> 
> ```
>  {
>     provide: MATERIAL_SANITY_CHECKS, 
>     useValue: false
>  }
> ```

Has anyone found a way to enable this for a whole Nx monorepo? Visiting all tests and testbeds to add this `provider` when an Angular Material part is being used feels a little, strange and time consuming.

**Comment by viceice** [comment]
> I just corrected ESM tests in `examples` of this repo but couldn’t see the issue like yours, see https://github.com/thymikee/jest-preset-angular/actions/runs/1257005889 Our examples don’t have `nx`

Your tests use `tslib@2.3.0` and i wrote above, it happened when I upgrade to `tslib@2.3.1`

https://github.com/thymikee/jest-preset-angular/blob/ce41947b6d981eb1a1a1371bd17884bb705e9c23/examples/example-app-v12-monorepo/yarn.lock#L8441-L8444

**Comment by ahnpnl** [comment]
I upgraded `tslib` to **2.3.1** https://github.com/thymikee/jest-preset-angular/pull/1025 but still couldn't see the same issue you had.

**Comment by nickroberts** [comment]
> > in you test you can set in providers this:
> > ```
> >  {
> >     provide: MATERIAL_SANITY_CHECKS, 
> >     useValue: false
> >  }
> > ```
> 
> Has anyone found a way to enable this for a whole Nx monorepo? Visiting all tests and testbeds to add this `provider` when an Angular Material part is being used feels a little, strange and time consuming.

I would like to know how to handle this globally in an Nx repo, as well. Doing this for every component might be a challenge.

**Comment by anatolie-darii** [comment]
> > in you test you can set in providers this:
> > ```
> >  {
> >     provide: MATERIAL_SANITY_CHECKS, 
> >     useValue: false
> >  }
> > ```
> 
> Has anyone found a way to enable this for a whole Nx monorepo? Visiting all tests and testbeds to add this `provider` when an Angular Material part is being used feels a little, strange and time consuming.

Just an idea. You can create a `MaterialTestingModule` that would import/export all your commonly used Material modules as well as this provider. Then use this in your tests instead of manually importing a bunch of material modules.

**Comment by MrTwisterAnastasia** [comment]
Hello everyone, maybe someone knows the reasons why this warning "Could not find Angular Material core theme.." may appear at all? 
In my app it was not there before, but as soon as I updated jest to 27.2 and jest-preset-angular to 10.0.1, it appeared ( all tests pass successfully and I dont have problems with Angular Material core theme in my angular-cli app in general ). 

Thank you in advance

**Comment by ahnpnl** [comment]
> Hello everyone, maybe someone knows the reasons why this warning "Could not find Angular Material core theme.." may appear at all? In my app it was not there before, but as soon as I updated jest to 27.2 and jest-preset-angular to 10.0.1, it appeared ( all tests pass successfully and I dont have problems with Angular Material core theme in my angular-cli app in general ).
> 
> Thank you in advance

The warning comes from Angular Material itself. You can bypass it by
```
providers: [{provide: MATERIAL_SANITY_CHECKS, useValue: false}]
```
see https://github.com/angular/components/issues/4125#issuecomment-347139081

**Comment by johncrim** [comment]
Here's one that I've encountered recently. Previously, our tsconfig had:

```json
  "include": [
    "**/*.spec.ts"
  ],
```

We did this to minimize the surface area that jest promises (since the *.spec files are the entrypoints). This worked fine before migrating to ES modules.

After [migrating to ES modules](https://thymikee.github.io/jest-preset-angular/docs/guides/angular-13+#using-es-modules), we started seeming some difficult-to-fix errors that seemed to indicate the interface imports are occasionally missing. For example:

```
 FAIL   Angular Tests  libs/logging/src/logging.service.spec.ts
  ● Test suite failed to run

    SyntaxError: The requested module '../model/logging-config' does not provide an export named 'LoggingConfig'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:779:5)
```

The file has the exported interface `LoggingConfig`, in spite of the error message. It is expected that typescript removes the export from the js file, and removes the import from the importing js file - this worked fine previously.

The "fix" turned out to be updating tsconfig.json to:
```
  "include": [
    "**/*.ts"
  ],
```

This seems to slow the tests down, but they work. There's a case to be made that this should be filed as a bug instead of an issue + solution, but as far as I can tell from looking at the code this is in the ts compiler, not jest-preset-angular.

I have not been able to create a simple repro for this - it definitely doesn't happen for all interface imports. My theory is that it happens when there are multiple files importing the interface, and it may be a race condition related to ordering of file transformation.

**Comment by johncrim** [comment]
Here's another one that you'll probably run into when migrating to ES modules. When migrating to ESM, you'll need to [add `@jest/globals` imports to all your test files that use `jest` and `expect` globals](https://jestjs.io/docs/ecmascript-modules#differences-between-esm-and-commonjs). This will break any expect extensions you are using (eg `@ngneat/spectator`, `jest-extended`), with errors like:

```
FAIL  src/expect-extension-jest-globals.spec.ts
  ● Test suite failed to run

    src/expect-extension-jest-globals.spec.ts:6:18 - error TS2339: Property 'toIncludeSameMembers' does not exist on type 'Matchers<void, number[]>'.
```

The cause it that the type that `@jest/globals: expect()` returns is different from the type non ESM `expect()` returns, which breaks all the type merging for extensions. I've [filed the bug with jest, and documented a workaround](https://github.com/facebook/jest/issues/12267).

**Comment by Lonli-Lokli** [comment]
I got this during latest update o the angular13, what can be the reason?
```
**\node_modules\@angular\core\node_modules\tslib\tslib.es6.js:24
    export function __extends(d, b) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```

**Comment by Lonli-Lokli** [comment]
@Bjeaurn I take an example_v13 from this repository as an example and it's not reproduces there. But there are some differences for yarn install in them
1) my repository with no yarn.lock & no node_modules produces node_modules/@angular/core/node_modules/tslib folder (which is mentioned in error)
2) example_v13 do not have internal node_module at all

I do not know what can cause this behaviour? Both installs happens on same machine, same yarn, without yarn.lock & root node_modules

**Comment by jbeckton** [comment]
While converting an Angular 12 app from Jasmine I am seeing some strange issues like...

`A "describe" callback must not return a value.`

here is the test...

````
describe('PayCalendarsComponent', async () => {
  it.skip('do nothing', () => { });
});
````

**Comment by johncrim** [comment]
@jbeckton  - your describe should not be async; move the `async` to the lambda in the `it()`.

**Comment by Adrii77** [comment]
Hello ! 

I'm facing an issue since my upgrade to Angular 14 and jest-preset-angular 12.X.X.
Those upgrades broke 8 (I have1 100) snapshots tests with storyshots from Storybook.

I tried many things, but nothing seems to work... :(

### Configuration

ng version
```
Angular CLI: 14.0.2
Node: 14.17.5
Package Manager: npm 6.14.14 
OS: linux x64

Angular: 14.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.3
webpack                         5.73.0
```

jest.config.js
```
const { defaults: jestNgPreset } = require('jest-preset-angular/presets');

/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  verbose: true,
  rootDir: '../',
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/.storybook/setup-jest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  globals: {
    "ts-jest": {
      ...jestNgPreset.globals['ts-jest'],
    // I created a specific tsconfig as I'm using Jest for snapshots testing only.
      tsconfig: '<rootDir>/tsconfig.snapshots.json',
    },
  },
  transform: {
    ...jestNgPreset.transform,
    '^.+\\.stories\\.mdx?$': '<rootDir>/.storybook/empty.js',
  },
  transformIgnorePatterns: ['node_modules/(?!@storybook/addon-docs|@angular|primeng|angular-auth-oidc-client)'],
  moduleNameMapper: {
    'jest-preset-angular/build/setup-jest': 'jest-preset-angular/setup-jest',
    'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer': 'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/AngularSnapshotSerializer': 'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/HTMLCommentSerializer': 'jest-preset-angular/build/serializers/html-comment',
  }
};
```
tsconfig.snapshots.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "outDir": "./out-tsc/spec",
    "module": "CommonJS",
    "types": ["jest"]
  },
  "include": ["src/**/*.d.ts"],
  "exclude": ["../src/**/*.spec.ts", "../src/test.ts"]
}
```

### Error
```
This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.
    This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

    Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors.
```

Components which fail have on thing in common : they inject 2 dependencies (`Window` and `AppSettings`) which are not decorated as Injectable (I provide them directly in one module, into the `providers` property). I specify that my app build/run well and my unit tests with Karma/Jasmine runs well too.

If someone has an idea.... Thanks by advance !

**Comment by Trolejbus** [comment]
In last PrimeNg releases (> v16), they have added `@layer primeng {}` at-rule to their component's css stylesheets. And looks like JSDom cannot handle at-rules - it is throwing:

```
Error: Could not parse CSS stylesheet
          at exports.createStylesheet (C:\sources\creditboard-new\CreditBoard\ClientApp\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:34:21)
...
 detail: '@layer primeng{p-inputnumber,.p-inputnumber{display:inline-flex}...
``` 

Looks like JSDom is not supporting at-rules: https://github.com/jsdom/jsdom/issues/2177.
So far preventing this error from showing up in console is working:

setup-jest.ts:
```javascript
function hideJsdomCssParsingIssue() {
  const originalConsoleError = console.error;
  const jsDomCssError = 'Error: Could not parse CSS stylesheet';
  console.error = (...params) => {
    if (!params.find(p => p.toString().includes(jsDomCssError))) {
      originalConsoleError(...params);
    }
  };
}
``` 

But I am not sure how to fix entirely this issue.

**Comment by johncrim** [comment]
@Trolejbus - I would look at the source for jsdom stylesheets.js. jsdom doesn't handle CSS, and doesn't do any layout. So it's not surprising that a DOM CSS method is stubbed out, thought I do find the error message a little surprising.

If you need layout (or CSS) support for your test, move it to karma.

**Comment by Trolejbus** [comment]
@johncrim - I have created issue for it: https://github.com/thymikee/jest-preset-angular/issues/2194. Case here is that it is sounds like not an issue with jest-preset-angular itself, but it will occur when installing most recent angular with most recent primeng version and trying to use jest-preset-angular. So I believe it is very common setup.

This issue is also reported for PrimeNg team: https://github.com/primefaces/primeng/issues/14085

**Comment by Badisi** [comment]
I'm not sure whether this is a bug or a misconfiguration on my side, but I can't seem to have `jest-preset-angular` to work with an Angular library's schematic. Especially when importing `@angular-devkit/core`.

I have detailed everything in this reproducible repo: https://github.com/badisi/issue-jest-with-schematics and already asked for help in **reactiflux#help-js** but got none.. I hope someone here could help me out. Thanks!

**Comment by MykhailoIskiv** [comment]
I've tried to migrate to es modules, as in [v17](https://github.com/thymikee/jest-preset-angular/tree/main/examples/example-app-v17) example, but haven't noticed performance improvements, it even work slower for me.
Maybe due to issues and how I've fixed it

1. rxjs in [moduleNameMapper](https://github.com/thymikee/jest-preset-angular/blob/main/examples/example-app-v17/jest-esm.config.mjs#L11)
```
moduleNameMapper: {
  ...pathsToModuleNameMapper(tsconfig.compilerOptions.paths, { prefix: '<rootDir>' }),
  tslib: 'tslib/tslib.es6.js',
  rxjs: '<rootDir>/node_modules/rxjs/dist/bundles/rxjs.umd.js',
},
```
the issue is that overrides everything that has rxjs in path, for example angular [`rxjs-interop`](https://angular.dev/guide/signals/rxjs-interop)
the fix, is to check that it starts with rxjs ('^rxjs')

```
moduleNameMapper: {
  ...pathsToModuleNameMapper(tsconfig.compilerOptions.paths, { prefix: '<rootDir>' }),
  tslib: 'tslib/tslib.es6.js',
  '^rxjs': '<rootDir>/node_modules/rxjs/dist/bundles/rxjs.umd.js',
},
```

2.  rxjs/webSocket
In my code I import webSocket from rxjs
`import { webSocket } from 'rxjs/webSocket';`
and for some reason it is not properly unwrapped in unit tests
I get `TypeError: webSocket is not a function` error

when I log the webSocket, I get
```
webSocket {
  webSocket: [Function: webSocket],
  WebSocketSubject: [Function: WebSocketSubject]
}
```
instead of 
```
webSocket [Function: webSocket]
```
Not sure that is a proper way to fix it, I've added the following to [`jest-global-mocks.ts`](https://github.com/thymikee/jest-preset-angular/blob/main/examples/example-app-v17/setup-jest-esm.ts#L2)

```
import { jest } from '@jest/globals';

jest.mock('rxjs/webSocket', () => {
  return {
    ...(jest.requireActual('rxjs/webSocket') as object),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    webSocket: (jest.requireActual('rxjs/webSocket') as any).webSocket
      .webSocket,
  };
});
```

3. Issue with [Leaflet](https://www.npmjs.com/package/leaflet) and it's extension [@geoman-io/leaflet-geoman-free](@geoman-io/leaflet-geoman-free)
For it I got issues like `You are trying to `import` a file after the Jest environment has been torn down.`
```
Test suite failed to run
ReferenceError: L is not defined

at node_modules/@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.js:2:93715
at Object.<anonymous> (node_modules/@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.js:2:225257)
```
I've fixed it by adding following to [`jest-global-mocks.ts`](https://github.com/thymikee/jest-preset-angular/blob/main/examples/example-app-v17/setup-jest-esm.ts#L2)
```
Object.defineProperty(window, 'L', {
  writable: true,
  value: jest.requireActual('leaflet'),
});
```
