### ISSUE TITLE
Cannot read property 'createStringLiteral' of undefined when using jest-27

### ISSUE THREAD

**Issue by NicolasTsc** [thymikee/jest-preset-angular#925]
## 🐛 Bug Report

Once I updated the package-json versions of jest and ts-jest to 27.0.1 I can`t run dummy tests anymore, because of there error:

```
Test suite failed to run

    TypeError: Cannot read property 'createStringLiteral' of undefined

      at Object.getCreateStringLiteral (../../node_modules/jest-preset-angular/build/TransformUtils.js:5:12)
      at ../../node_modules/ts-jest/dist/compiler/ts-compiler.js:169:42
          at Array.map (<anonymous>)
      at TsCompiler._makeTransformers (../../node_modules/ts-jest/dist/compiler/ts-compiler.js:168:47)
      at Object.getCustomTransformers (../../node_modules/ts-jest/dist/compiler/ts-compiler.js:219:63)
      at Object.getEmitOutput (../../node_modules/typescript/lib/typescript.js:149946:73)
      at TsCompiler.getCompiledOutput (../../node_modules/ts-jest/dist/compiler/ts-compiler.js:128:48)
      at TsJestCompiler.getCompiledOutput (../../node_modules/ts-jest/dist/compiler/ts-jest-compiler.js:13:39)
      at TsJestTransformer.process (../../node_modules/ts-jest/dist/ts-jest-transformer.js:146:37)
```
## To Reproduce

Create example nrwl angular project, upgrade jest to 27.0.1 and run dummy tests

## Expected behavior

Tests working

```
System:
    OS: Windows 10

Npm packages:
    jest: 27.0.1
    jest-preset-angular: 8.4.0
    typescript: 4,2,4
```

**Comment by ahnpnl** [comment]
you can try out `next` tag, we will release **9.0.0** soon so you can ignore warnings in `next` tag and see if `next` tag works for you.

**Comment by aakaul** [comment]
i am facing same issue next tag is not working form me

**Comment by ahnpnl** [comment]
have you tried clearing Jest cache?

If you are using nrwl nx, you should wait for them to add support because there are migration needed on their side.

If you are NOT using nrwl nx, you can try clear Jest cache via `jest --clearCache`. If still not working, please provide a repo.

**Comment by ahnpnl** [comment]
For nrwl nx, see https://github.com/nrwl/nx/issues/5771

**Comment by aakaul** [comment]
hi i am not using nrwl

**Comment by ahnpnl** [comment]
you should try clearing Jest cache after upgrading to `next` tag.

**Comment by aakaul** [comment]
i tried clearing cache 

Steps to repo 
`npm install jest jest-preset-angular @types/jest --save-dev`
`npm install ts-jest@next` => i was facing TypeError: Jest: a transform must export something.
`npm install jest-preset-angular@next` 
jest --clearCache

env:
node v14.15.0
typescript: 4.0.5
jest-preset-angular: 9.0.0-next.14
jest: 27.0.1
ts-jest: 27.0.0-next.12
angular:11.2
OS: OSX 11.2.2

**Comment by ahnpnl** [comment]
hmm i still cannot reproduce your issue @aakaul

**Comment by aakaul** [comment]
ok cool. @ahnpnl  thanks i will downgrade the packages

**Comment by NicolasTsc** [comment]
Here is a minimal repo @ahnpnl 
https://github.com/NicolasTsc/jest-angular

**Comment by ahnpnl** [comment]
@NicolasTsc  please wait for `jest-preset-angular` **9.0.0**. **8.4.0** doesn't work with jest 27

**Comment by NicolasTsc** [comment]
@ahnpnl okay any estimated date for it yet?

**Comment by ahnpnl** [comment]
Either this week or beginning of next week

**Comment by NicolasTsc** [comment]
I now receive another error when using version 9.0.0:

```
  ● Test suite failed to run

    File not found: jest-preset-angular/build/InlineFilesTransformer (resolved as: C:\Users\tschirr\Documents\frontend\jest-preset-angular\build\InlineFilesTransformer)

      at ConfigSet.resolvePath (node_modules/ts-jest/dist/config/config-set.js:444:19)
      at node_modules/ts-jest/dist/config/config-set.js:225:46
          at Array.map (<anonymous>)
      at resolveTransformers (node_modules/ts-jest/dist/config/config-set.js:223:37)
      at ConfigSet._setupConfigSet (node_modules/ts-jest/dist/config/config-set.js:233:137)
      at new ConfigSet (node_modules/ts-jest/dist/config/config-set.js:142:14)
      at NgJestTransformer.TsJestTransformer._createConfigSet (node_modules/ts-jest/dist/ts-jest-transformer.js:111:16)
      at NgJestTransformer.TsJestTransformer._configsFor (node_modules/ts-jest/dist/ts-jest-transformer.js:89:34)
      at NgJestTransformer.TsJestTransformer.getCacheKey (node_modules/ts-jest/dist/ts-jest-transformer.js:172:28)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:280:41)
```
I updated my example repo: https://github.com/NicolasTsc/jest-angular

**Comment by ahnpnl** [comment]
Please check our CHANGELOG. 9.0.0 is a breaking change so migration is required. Things require migration are mentioned in CHANGELOG.
