### ISSUE TITLE
Jest 27 Support

### ISSUE THREAD

**Issue by michaelfaith** [thymikee/jest-preset-angular#934]
## 🐛 Bug Report

I tried updating to Jest 27 just now, and receiving this TypeError about transforms.  

## To Reproduce

Update to Jest 27.0.0 and run jest.

## Error log:

```
# content of error stacktrace :
TypeError: Jest: a transform must export something.
    at C:\Users\user\src\fabric\node_modules\@jest\transform\build\ScriptTransformer.js:386:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async ScriptTransformer.loadTransformers (C:\Users\user\src\fabric\node_modules\@jest\transform\build\ScriptTransformer.js:378:5)
    at async createScriptTransformer (C:\Users\user\src\fabric\node_modules\@jest\transform\build\ScriptTransformer.js:1105:3)
    at async C:\Users\user\src\fabric\node_modules\@jest\core\build\TestScheduler.js:283:31
    at async Promise.all (index 0)
    at async TestScheduler.scheduleTests (C:\Users\user\src\fabric\node_modules\@jest\core\build\TestScheduler.js:276:5)
    at async runJest (C:\Users\user\src\fabric\node_modules\@jest\core\build\runJest.js:387:19)
    at async _run10000 (C:\Users\user\src\fabric\node_modules\@jest\core\build\cli\index.js:408:7)

```

## envinfo

```
System:
    OS: Windows

Npm packages:
    jest: 27.0.0
    jest-preset-angular: 8.4.0
    typescript: 4.2.4
```

**Comment by ahnpnl** [comment]
please use 9.0.0 which was just out

**Comment by michaelfaith** [comment]
Thank you!  I didn't see it on NPM earlier.  I'll give it a try.
