### ISSUE TITLE
zone-testing.js is needed for the fakeAsync() test helper but could not be found.

### ISSUE THREAD

**Issue by thovo** [thymikee/jest-preset-angular#947]
## 🐛 Bug Report

I used Angular CLI to create a new Angular project and I was trying to replace Karma with Jest. Follow the tutorial on the Internet, I went to the last step to run the test and got this error:

> zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

I was trying to downgrade the version of jest, ts-jest, @types/jest to find a workable version but I didn't get it yet. The error with zone seems gone with jest 26, ts-jest 26 but I got another error like this one https://github.com/kulshekhar/ts-jest/issues/2611
I already installed Node 14, clear jest cache, deleted and reinstalled node_modules but I still had this error

## To Reproduce

1. Clone the repo below
2. `yarn install`
3. `yarn test`

## Expected behavior

Expect test worked without errors

## Link to repo (highly encouraged)
https://github.com/thovo/angular-todo-app

## Error log:

```
# content of error stacktrace :
AppComponent
    × should create the app (1 ms)
    × should have as title 'angular-todo-app'
    × should render title (1 ms)

  ● AppComponent › should create the app

    zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing

      at resetFakeAsyncZone (../packages/core/testing/src/fake_async.ts:25:9)
      at Object.<anonymous> (../packages/core/testing/src/before_each.ts:26:5)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

  ● AppComponent › should have as title 'angular-todo-app'

    zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

  ● AppComponent › should render title

    zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing

      at resetFakeAsyncZone (../packages/core/testing/src/fake_async.ts:25:9)
      at Object.<anonymous> (../packages/core/testing/src/before_each.ts:26:5)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)
```

## envinfo

```
System:
    OS: Windows 10

Npm packages:
    jest: 27.0.4
    jest-preset-angular: 9.0.1
    typescript: 4.3.2
```

**Comment by ahnpnl** [comment]
Please check our README as well as documentation for installation and configuration step.

In short, you didn’t import setup file which is provided by `jest-preset-angular`.

We also have `examples` folder which you can check how the project should setup to work with jest.

**Comment by thovo** [comment]
@ahnpnl thanks a lot, I just followed the tutorial on the internet, should check the Readme first.
