### ISSUE TITLE
Component is not resolved ... Did you run and wait for 'resolveComponentResources()'?

### ISSUE THREAD

**Issue by mlc-mlapis** [thymikee/jest-preset-angular#951]
## To Reproduce

* Install the default workspace with a single Angular application using `npx create-nx-workspace@latest` command.
* Updating packages:
```
"jest": "27.0.4",
"jest-preset-angular": "9.0.3",
"ts-jest": "27.0.3"
```
* Updating the root `jest.config.js` to:
```
require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
  projects: ['<rootDir>/apps/test'],
};
```
* Updating the application `jest.config.js` to:
```
module.exports = {
  displayName: 'test',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$'
    }
  },
  coverageDirectory: '../../coverage/apps/test',
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment'
  ]
};
```
Updating `"postinstall": "node ./decorate-angular-cli.js && ngcc"` and repeating `npm i` to generate UMD packages.

Run `npm run test`.

Result:
```
Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
Did you run and wait for 'resolveComponentResources()'?
```

## Expected behavior

Correct test processing as with default setting and versions of:

```
"jest": "26.2.2",
"jest-preset-angular": "8.4.0",
"ts-jest": "26.5.5"
```
## Error log:

```
nx run test:test 
 FAIL   test  apps/test/src/app/app.component.spec.ts
  AppComponent
    × should create the app (10 ms)
    × should have as title 'test' (2 ms)
    × should render title (1 ms)

  ● AppComponent › should create the app

    Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?

      at Function.get (../../../packages/core/src/render3/jit/directive.ts:82:17)
      at getComponentDef (../../../packages/core/src/render3/definition.ts:735:14)
      at verifyDeclarationsHaveDefinitions (../../../packages/core/src/render3/jit/module.ts:242:17)
          at Array.forEach (<anonymous>)
      at verifySemanticsOfNgModuleDef (../../../packages/core/src/render3/jit/module.ts:212:16)
      at Function.get (../../../packages/core/src/render3/jit/module.ts:167:13)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.applyProviderOverridesToModule (../../../packages/core/testing/src/r3_test_bed_compiler.ts:414:49)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.compileTestModule (../../../packages/core/testing/src/r3_test_bed_compiler.ts:677:10)
      at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.finalize (../../../packages/core/testing/src/r3_test_bed_compiler.ts:245:10)
      at TestBedRender3.get (../../../packages/core/testing/src/r3_test_bed.ts:370:43)
```

## envinfo

```
System:
    OS: Windows 10, NodeJS 14.17.0

Npm packages:
    jest: 27.0.4
    jest-preset-angular: 9.0.3
    typescript: 4.2.4
```

**Comment by ahnpnl** [comment]
this is because Nrwl Nx needs to have migration for Jest config. In root `jest-preset.js`, 
```
const nxPreset = require('@nrwl/jest/preset');

module.exports = { ...nxPreset };
```

which refers to `node_modules/@nrwl/jest/preset/jest-preset.js`, the config should be
```
module.exports = {
    testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
    resolver: '@nrwl/jest/plugins/resolver',
    moduleFileExtensions: ['ts', 'js', 'html'],
    coverageReporters: ['html'],
  testEnvironment: 'jsdom', <=== Jest 27 default testEnvironment is node
    transform: {
        '^.+\\.(ts|js|html)$': 'jest-preset-angular', <=== breaking change in 9.0.0
    },
};
```

If you want to use Jest 27, you need to override root `jest-preset.js` with the config above or wait for Nrwl Nx team to release a new version.

**Comment by mlc-mlapis** [comment]
@ahnpnl Great! I tried several combinations before, but with no luck. So your tip was great, and it works now. Thanks once more. 🏅

**Comment by yharaskrik** [comment]
@mlc-mlapis do you mind sharing exactly what it was that fixed your issue? I just upgraded out Nx workspace to 12.4.0 (which has the migration that @ahnpnl mentions, ie. `testEnvironment: 'jsdom'` in the root) but I am getting the same error as you still. This is all the code is

```
import { async, TestBed } from '@angular/core/testing';
import { FundraiserPageEditorPublishDialogModule } from './fundraiser-page-editor-publish-dialog.module';

describe('FundraiserPageEditorPublishDialogModule', () => {
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [FundraiserPageEditorPublishDialogModule],
        }).compileComponents();
    }));

    it('should create', () => {
        expect(FundraiserPageEditorPublishDialogModule).toBeDefined();
    });
});
```

`jest-preset-angular: 9.0.3`
`jest: 27.0.3`
`ts-jest: 27.0.3`

I tried to override test environment in the projects jest.config.js as well but no dice.

**Comment by mlc-mlapis** [comment]
@yharaskrik I am using already `"jest-preset-angular": "9.0.4"`.

My root `jest.preset.js`:

```
const nxPreset = require('@nrwl/jest/preset');

module.exports = {
	...nxPreset,
	testEnvironment: 'jsdom',
    transform: {
        '^.+\\.(ts|js|html)$': 'jest-preset-angular'
    }
};
```

My root `jest.config.js`:

```const ngccPreset = require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
    projects: [
        ...
    ],
};

```

**Comment by yharaskrik** [comment]
Hmm that is odd. I will try and see if i can figure out what is going on. Why do you require the ngcc jest procesor? I don't need the default created workspace by Nx doing that.

**Comment by mlc-mlapis** [comment]
@yharaskrik Yep, it shouldn't be necessary for you. It was mentioned, so I tried to do all steps.

**Comment by Vchouliaras** [comment]
I had the same issue. However no luck even after trying the above.

```
"jest": "27.0.6",
"jest-preset-angular": "9.0.4",
 ```

**Comment by jdnichollsc** [comment]
Check this other configuration for Nx:
```
const jestPresetAngularSerializers = require('jest-preset-angular/build/serializers')

module.exports = {
  displayName: 'app',
  preset: '../../jest.preset.js',
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$'
    },
  },
  coverageDirectory: '../../coverage/apps/app',
  snapshotSerializers: jestPresetAngularSerializers,
};
```

**Comment by Nirmalkusahoo** [comment]
just in case it help anyone
I was getting this error ,since I was using closing tag for input
 <input type="checkbox" ></input>
 
 changing this to <input type="checkbox"> worked for me

**Comment by jane-taleika** [comment]
Same issue, nothing from above helped

```
"jest": "27.0.3",
"jest-preset-angular": "9.0.3"
```

**Comment by eng-dibo** [comment]
+1
the test runs correctly with `ng test` but fails with `jest` and it complains for resolving the template

```
 Component 'AppComponent' is not resolved:
     - templateUrl: ./app.component.html
     - styleUrls: ["./app.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
```
it is a fresh angular project created with angular cli

**Comment by ahnpnl** [comment]
https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy

**Comment by juristr** [comment]
@eng-dibo Make sure in the `jest.config.js` you use something like

```
  transform: { '^.+\\.(ts|js|html)$': 'jest-preset-angular' },
```

**Comment by jane-taleika** [comment]
In my case problem was in wrong imports. Replacing import from "@ngneat/spectator" to "@ngneat/spectator/jest" solved this error.

**Comment by YoeriNijs** [comment]
Changed my configuration to this actually fixed the issue: 

_./jest.config.js_
```
module.exports = {
  name: 'config',
  preset: '../../jest.config.base.js',
  globals: {
    'ts-jest': {
      stringifyContentPathRegex: '\\.(html|svg)$',
      tsconfig: '<rootDir>/tsconfig.spec.json',
      astTransformers: {
        before: [
          'jest-preset-angular/build/InlineFilesTransformer',
          'jest-preset-angular/build/StripStylesTransformer'
        ]
      }
    }
  },
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment'
  ],
  setupFilesAfterEnv: [
    './src/test-setup.ts'
  ],
};

```

_./src/test-setup.ts_
`import 'jest-preset-angular/setup-jest';`

**Comment by cataclysm-jude2** [comment]
@jdnichollsc https://angulardev.space/questions/running-a-function-using-a-component-in-angular-5
