### ISSUE TITLE
Unable to use services exported under a namespace w/ Jest 27 + Ng12

### ISSUE THREAD

**Issue by AgentEnder** [thymikee/jest-preset-angular#963]
## 🐛 Bug Report

Attempting to test components that inject a service imported from a namespace fails in Jest 27 / Angular 12.

## To Reproduce

1. `ng new my-app`
2. Install jest / jest-preset-angular
3. Create a new folder, services.
4. Create a file in that folder (my-service.ts) containing the following:
```typescript
import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class MyService {
    constructor() {
        console.log('HELLO')
    }
}
```
5. Create a new file (index.ts) inside the services folder containing the following:
```typescript
import * as Services from './my-service';

export { Services }
```
6. Add `private myService: Services.MyService` to the constructor of app-component
7. Import Services in app-component.
8. Try to run tests with `npx jest`

## Expected behavior

Tests run successfully

## Link to repo (highly encouraged)

https://github.com/AgentEnder/ng-jest-issue-6097

## Error log:

```
 Can't resolve all parameters for AppComponent: (?).

      at syntaxError (../packages/compiler/src/util.ts:108:17)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver._getDependenciesMetadata (../packages/compiler/src/metadata_resolver.ts:1010:27)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver._getTypeMetadata (../packages/compiler/src/metadata_resolver.ts:889:20)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (../packages/compiler/src/metadata_resolver.ts:387:18)
      at CompileMetadataResolver.Object.<anonymous>.CompileMetadataResolver.loadDirectiveMetadata (../packages/compiler/src/metadata_resolver.ts:238:41)
      at ../packages/compiler/src/jit/compiler.ts:137:36
          at Array.forEach (<anonymous>)
      at ../packages/compiler/src/jit/compiler.ts:135:65
          at Array.forEach (<anonymous>)
      at JitCompiler.Object.<anonymous>.JitCompiler._loadModules (../packages/compiler/src/jit/compiler.ts:132:71)
      at JitCompiler.Object.<anonymous>.JitCompiler._compileModuleAndAllComponents (../packages/compiler/src/jit/compiler.ts:117:32)
      at JitCompiler.Object.<anonymous>.JitCompiler.compileModuleAndAllComponentsAsync (../packages/compiler/src/jit/compiler.ts:69:33)
      at CompilerImpl.Object.<anonymous>.CompilerImpl.compileModuleAndAllComponentsAsync (../packages/platform-browser-dynamic/src/compiler_factory.ts:69:27)
      at TestingCompilerImpl.Object.<anonymous>.TestingCompilerImpl.compileModuleAndAllComponentsAsync (../packages/platform-browser-dynamic/testing/src/compiler_factory.ts:59:27)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.compileComponents (../packages/core/testing/src/test_bed.ts:366:27)
      at Function.Object.<anonymous>.TestBedViewEngine.compileComponents (../packages/core/testing/src/test_bed.ts:155:25)
      at src/app/app.component.spec.ts:10:8
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)

```

## envinfo

```
System:
    OS: Ubuntu (tested under wsl2)

Npm packages:
    jest: 27.0.5
    jest-preset-angular: 9.0.4
    typescript: 4.2.3
```

**Comment by wtho** [comment]
Does the same setup work in Angular v11 with same jest/ts-jest/jest-preset-angular versions?

**Comment by ahnpnl** [comment]
I debugged and saw that the compiled output of `AppComponent` contains `undefined` as ctor parameter, which causes the issue. The problem could be that TypeScript `LanguageService` couldn't resolve the import from export namespace.

**Comment by ahnpnl** [comment]
The bug should occur to Angular 11 too as we use the same transformer. 

One unknown thing is why Karma + Jasmine works. The most suspicious point would be module resolution doesn’t work correctly which makes `LanguageService` not able to find the information of the file.

**Comment by pheinicke** [comment]
Hi,
I have the exact same issue as @Maximaximum. That is Angular 12, Jest and code generated by a third party tool, containing namespace imports.
@ahnpnl How would you tell Jest to run on the compiled files?

Thanks for the help!

**Comment by ahnpnl** [comment]
You can configure where Jest should look for the files by using `testMatch`, `testRegex`, `rootDir`. I think mainly `rootDir`, see https://jestjs.io/docs/configuration#rootdir-string

You have to use `ngc` to compile, don’t use `tsc`

**Comment by Maximaximum** [comment]
Fwiw, in the title of this issue "exported" should be replaced with "imported", because it's not the export syntax, but the import syntax that causes the issue

**Comment by Maximaximum** [comment]
FWIW I'm now trying to use the 2nd workaround suggested by @ahnpnl. But what drastically complicates things even more is that I'm having an `nx` workspace with about 20 different nx projects, instead of just a single Angular project. There doesn't seem to be a way to run `ngc` for every nx project automatically. And even if there was, I'm not sure where does the `ngc` output go, and how to make sure that jest is run against the built files, not against the sources.

Looks like I'm stuck with adding any unit tests to my project right now. Neither applying a workaround for jest, nor reverting back to using karma seems to be an easy thing to do.

**Comment by ahnpnl** [comment]
`ngc` can be configured but you would need to find documentation online.

**Comment by Maximaximum** [comment]
I can't find documentation about configuring the output folder here https://angular.io/guide/angular-compiler-options. Does `ng build` do the same thing as `ngc`? Should we run jest against the bundled files located in the `dist` folder, produced by `ng build`?

**Comment by ahnpnl** [comment]
IIRC `ng build` does similar thing like `ngc`. `ngc` is a replacement of `tsc` which does some Angular things extra.

After producing build outputs, you would need to configure Jest to run on output folder yes.

**Comment by ahnpnl** [comment]
Hi all, I found an easy workaround for this issue. You can configure Jest `moduleNameMapper` to instruct Jest to load the correct module. With the example repo from @AgentEnder, the configuration will be
```
// jest.config.js
module.exports = {
   moduleNameMapper: {
       './services$': '<rootDir>/src/app/services/demo-service.ts'
   }
}
```

**Comment by Maximaximum** [comment]
@ahnpnl I'm currently trying to implement a custom Jest resolver, but it seems like a customer resolver won't be able to fix the issue.

Let's take a `import * as Apollo from 'apollo-angular';` line as an example.

As far as I can see, a Jest resolver only deals with resolving `import` paths like `apollo-angular` to actual absolute file paths in the filesystem (like `/workspaces/my-project/frontend/node_modules/apollo-angular/bundles/ngApollo.umd.js`). But it has nothing to do with handling the `* as Apollo` part. The resolver doesn't even get the `* as Apollo` (or anything like `{ gql }` or `someDefaultExport`) part as an argument, it has no idea about what values are actually being imported from an es6 module.

**Comment by Maximaximum** [comment]
I was finally able to create a workaround that seems to solve the issue (at least for me) and lets angular+jest unit tests with namespace imports actually run: https://github.com/Maximaximum/jest-namespace-imports-transformer

I still hope that the `jest-preset-angular` team is going to address this issue within `jest-preset-angular` itself so that my workaround (which might be quite buggy) won't be needed anymore.

**Comment by ahnpnl** [comment]
I guess all the logic to desugar namespace syntax lies here https://github.com/Maximaximum/jest-namespace-imports-transformer/blob/main/src/transform-script.ts#L88 ? We are happy to add it as a custom AST transformer to internal codes

**Comment by Maximaximum** [comment]
@ahnpnl Yes, that would be great! I can't guarantee my workaround works nicely for all cases and scenarios (I'm a total newbie with regards to `Typescript compiler API`, `jest` and `jest-preset-angular`, so I have easily messed up something), but so far so good: it works for me.

**Comment by Nielsb85** [comment]
> @ahnpnl Yes, that would be great! I can't guarantee my workaround works nicely for all cases and scenarios (I'm a total newbie with regards to `Typescript compiler API`, `jest` and `jest-preset-angular`, so I have easily messed up something), but so far so good: it works for me.

For me , when adding the transformer:
```

 ● Test suite failed to run

    Cannot find module './jest-transformer'
    Require stack:
    - /client/node_modules/jest-namespace-imports-transformer/dist/index.js
    - /client/node_modules/@jest/core/node_modules/jest-util/build/requireOrImportModule.js
    - /client/node_modules/@jest/core/node_modules/jest-util/build/index.js
    - /client/node_modules/@jest/core/build/FailedTestsInteractiveMode.js
    - /client/node_modules/@jest/core/build/plugins/FailedTestsInteractive.js
    - /client/node_modules/@jest/core/build/watch.js
    - /client/node_modules/@jest/core/build/cli/index.js
    - /client/node_modules/@jest/core/build/jest.js
    - /client/node_modules/jest/node_modules/jest-cli/build/cli/index.js
    - /client/node_modules/jest/node_modules/jest-cli/bin/jest.js
    - /client/node_modules/jest/bin/jest.js

      at Object.<anonymous> (node_modules/jest-namespace-imports-transformer/dist/index.js:16:44)

```

**Comment by ahnpnl** [comment]
@Maximaximum  I just found a new workaround that you can adjust your `tsconfig.spec.json` to have
```
{
   //...
  "include": ["src/**/*.ts"]
}
```
at least it fixed the issue with the sample repo.

The problem I think is similar to #1199 is that: Angular doesn't support transpile `ts` to `js` in "isolated way". Angular always requires one single TypeScript `Program` to process all the files together while here with Jest, we split them up into multiple workers. Compilation per worker is not the same as using one single `Program`.

**Comment by Maximaximum** [comment]
@ahnpnl Any news regarding properly fixing this issue within `jest-preset-angular`?

**Comment by DaSchTour** [comment]
> @Maximaximum I just found a new workaround that you can adjust your `tsconfig.spec.json` to have
> 
> ```
> {
>    //...
>   "include": ["src/**/*.ts"]
> }
> ```
> 
> at least it fixed the issue with the sample repo.
> 
> The problem I think is similar to #1199 is that: Angular doesn't support transpile `ts` to `js` in "isolated way". Angular always requires one single TypeScript `Program` (see [angular/angular#43165](https://github.com/angular/angular/issues/43165)) to process all the files together while here with Jest, we split them up into multiple workers. Compilation per worker is not the same as using one single `Program`.

This doesn't seam to work with nx repos and graphql codegen 😞

**Comment by bvklingeren** [comment]
I am using generated code from `apollo-angular` like @Maximaximum and was able to fix the issue with an `ngcc` run and the replacement of 
```
{
   //...
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```
with
```
{
   //...
  "include": ["**/*.ts"]
}
```
in `tsconfig.spec.json`

Currently using jest-preset-angular@9.0.7

**Comment by ibanjo** [comment]
> I am using generated code from `apollo-angular` like @Maximaximum and was able to fix the issue with an `ngcc` run and the replacement of
> 
> ```
> {
>    //...
>   "include": ["**/*.spec.ts", "**/*.d.ts"]
> }
> ```
> 
> with
> 
> ```
> {
>    //...
>   "include": ["**/*.ts"]
> }
> ```
> 
> in `tsconfig.spec.json`
> 
> Currently using jest-preset-angular@9.0.7

This workaround works for me, with the (possibly trivial) caveat that, if you're importing namespaced symbols from another library in your same workspace (e.g. when using Nx Workspaces), the `tsconfig.spec.json` to be patched is that in the consumer library (no need to touch the exporting lib as well).

**Comment by devmanbr** [comment]
any solution for this? the solutions found here did not work for me.

**Comment by jorgevds** [comment]
Hey friends, chiming in real quick to say that the change to tsconfig.spec.json:

```json
"include": ["src/**/*.ts"]
```

solved 1/3 of my issue. Changing my service and spec file name (yes, really) from:

hyphenated-name.sandbox.spec.ts

to

hyphenated-name-sandbox.service.spec.ts

fixed another third of my issue. 

After that, I started getting more specific Apollo errors, about "invariant" something this and "no provider for _Apollo" that. I solved those by including a defaultOptions object into my Apollo client setup that I use exclusively for unit tests, where before I only used the link and cache object keys. This is essentially a module (read: via static method) that sets the APOLLO_OPTIONS token with some fake values to be used in test.

Finally, optionally, for anyone using Nx and MSW who may be overlooking this, make sure your library's project.json test configuration has your mockServiceWorker.js file in its assets array, and that you setup your MSW server inside of your test-setup.ts file within your library's src folder.
