### ISSUE TITLE
Yarn Workspace Monorepo + Library Built with Angular 12 + Jest Throws an Error

### ISSUE THREAD

**Issue by michaelfaith** [thymikee/jest-preset-angular#980]
## 🐛 Bug Report

So, this is an interesting situation.  I'm responsible for a component library within our company, and we recently updated for Angular 12.  Part of Angular's guidance for library authors, is to compile with Partial Ivy starting in Angular 12.  An app that's using our library in an Angular project that's nested within a monorepo, using Yarn Workspaces, is failing to run tests on components that use stuff from our library, with the following error:

`Error: thrown: "Failed to load header.component.html"`

That html is a file nested (and built) within our library code.  It isn't even a template that's in the app project.  Just to test this out, I rebuilt the library with Ivy completely disabled, published it, installed it in the app and re-tested, and the tests run fine.  So it seems the Jest config is having trouble working with Partial Ivy libraries, when `node_modules` is hoisted to the top of the repo.   I found this issue in another library's repo, seeming to indicate the same problem after they build with Partial Ivy:  https://github.com/tiberiuzuld/angular-gridster2/issues/740

Another, possibly related issue, was resolved in the angular repo a year and a half ago.  Could point towards a possible solution  https://github.com/angular/angular/issues/35747

## To Reproduce

Setup monorepo with Yarn workspace.
Create new Angular app as a project within the monorepo with Jest configured
Install that angular-gridster2 library
Add one of their components to the app.component.html, and import the module into the spec
Run the test

## Expected behavior
Should run without error

## Link to repo (highly encouraged)

My repo is internal, but if you're unable to reproduce with the steps above, I can try and set something up.

## Error log:

```
Error: thrown: "Failed to load header.component.html"

    at context.<computed> (C:\Users\<user>\src\Atom\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:4309:39)
    at C:\Users\<user>\src\Atom\packages\GuideApp\src\app\app.component.spec.ts:55:3
    at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (C:\Users\<user>\src\Atom\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:407:30)
    at Zone.Object.<anonymous>.Zone.run (C:\Users\<user>\src\Atom\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:167:47)
    at C:\Users\<user>\src\Atom\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:4227:33
    at _dispatchDescribe (C:\Users\<user>\src\Atom\node_modules\jest-circus\build\index.js:97:26)
    at describe (C:\Users\<user>\src\Atom\node_modules\jest-circus\build\index.js:60:5)
    at context.<computed> (C:\Users\<user>\src\Atom\node_modules\zone.js\bundles\zone-testing-bundle.umd.js:4270:39)
    at Object.<anonymous> (C:\Users\<user>\src\Atom\packages\GuideApp\src\app\app.component.spec.ts:26:1)
    at Runtime._execModule (C:\Users\<user>\src\Atom\node_modules\jest-runtime\build\index.js:1394:24)
    at Runtime._loadModule (C:\Users\<user>\src\Atom\node_modules\jest-runtime\build\index.js:996:12)
    at Runtime.requireModule (C:\Users\<user>\src\Atom\node_modules\jest-runtime\build\index.js:828:12)
    at jestAdapter (C:\Users\<user>\src\Atom\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:79:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runTestInternal (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\jest-runner\build\runTest.js:389:16)
    at runTest (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\jest-runner\build\runTest.js:481:34)
    at TestRunner.runTests (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\jest-runner\build\index.js:111:12)
    at TestScheduler.scheduleTests (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\@jest\core\build\TestScheduler.js:333:13)
    at runJest (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\@jest\core\build\runJest.js:387:19)
    at _run10000 (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\@jest\core\build\cli\index.js:408:7)
    at runCLI (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\@jest\core\build\cli\index.js:261:3)
    at Object.run (C:\Users\<user>\src\Atom\packages\GuideApp\node_modules\jest-cli\build\cli\index.js:163:37)

```

## envinfo

```
System:
    OS: Windows 10

Npm packages:
    jest: 27.0.6
    jest-preset-angular: 9.0.4
    typescript: 4.3.5
```

**Comment by michaelfaith** [comment]
@ahnpnl I do have ngcc set as a postinstall step, so it did run, but libraries built with Partial Ivy don't require ngcc.  The whole point of ngcc is to convert a non-Ivy library to something compatible with Ivy.  Partial Ivy libraries come with Ivy compatibility.

**Comment by ahnpnl** [comment]
Hmm, did you see the error happening to normal workspace or is it only within Yarn workspace? The error looks to me like something related to Jest resolver which resolves some funny things.

**Comment by michaelfaith** [comment]
@ahnpnl it works fine with a normal single project yarn setup, where the node_modules are at the same level as the package.  It's only happening when using a monorepo and yarn workspaces, when the angular.json, and package is not at the root.  Ng serve and all of the angular related commands work fine, but jest is throwing that error.

**Comment by ahnpnl** [comment]
Have you tried to configure `moduleNameMapper`? Normally in a monorepo, that config is needed for some of your folders which isn’t provided by this preset. Looking at the error, I think that option should help.

**Comment by ahnpnl** [comment]
It looks to me in this case, Jest doesn’t load your dependencies coming from node_modules. We can verify this if you can produce the logging of `ts-jest`. Would you pls do that by following https://kulshekhar.github.io/ts-jest/docs/debugging I highly suspect the problem is with Jest module resolution.

**Comment by michaelfaith** [comment]
@ahnpnl I created a repo that demonstrates the bug.  I created a simple monorepo with yarn workspaces.  Generated a new angular app as the only package within it.  Swapped in Jest for Karma/Jasmine.  Added the gridster library that I linked above, which is compiling with Ivy Partial complication, and used one of their components in the app.component.  

If you clone that repo, run `yarn` to install the dependencies, then run `yarn repro`, it'll run jest in the lower package and show the failure.

https://github.com/michaelfaith/ang12-jest-yarn-bug

**Comment by literalpie** [comment]
Hi! I'm glad this issue is already being tracked because I'm also running into it. However, I don't think yarn monorepos have anything to do with the issue. I was able to reproduce it using a basic Angular project and angular-gridster2 [here](https://github.com/literalpie/ivy-partial-jest).

Hope this helps!

**Comment by michaelfaith** [comment]
@literalpie that's interesting.  The library I work on, which is built with partial Ivy, works fine in a regular single project setup.  It only presented this for me when nested in a monorepo

**Comment by ahnpnl** [comment]
@literalpie , it is a must to run `ngcc` before running Jest, otherwise Jest won't get the correct `umd` modules for Angular package format. In your repo, you can just put `require('jest-preset-angular/ngcc-jest-processor');` in your `jest.config.js` and the test will pass.

**Comment by michaelfaith** [comment]
@ahnpnl actually require('jest-preset-angular/ngcc-jest-processor') does work for hoisted modules.  When I run jest, it does the compile on all of those libraries.  But it does _not_ do it for Partial Ivy libraries, because, again those don't need to be run through ngcc.  ngcc = angular compatibility compiler.  Partial Ivy libraries are already compatible with Ivy, so ngcc doesn't touch them.

**Comment by michaelfaith** [comment]
And again, this works for all libraries that are build with View Engine (pre Angular 12 settings), with the monorepo and yarn structure.  If what your saying was the issue, it wouldn't work for those at all.

**Comment by ahnpnl** [comment]
What I did in your repo is:
- Run `yarn install`
- Run `ngcc` from root of the repo
- Run `yarn repro`

I see the test passed after those 3 steps. I'm not sure what else I should do?

**Comment by michaelfaith** [comment]
Oh wow, you're right.  What's interesting, is that ngcc didn't process the library at all.  And if I take that library out, jest runs fine.  So I guess it's confusing to me why ngcc would play into it all, if ngcc doesn't touch the library.

**Comment by michaelfaith** [comment]
This is what ngcc ends up processing:
```
Compiling @angular/core : fesm2015 as esm2015
Compiling @angular/animations : fesm2015 as esm2015
Compiling @angular/compiler/testing : fesm2015 as esm2015
Compiling @angular/animations : esm2015 as esm2015
Compiling @angular/animations : main as umd
Compiling @angular/compiler/testing : esm2015 as esm2015
Compiling @angular/compiler/testing : main as umd
Compiling @angular/common : fesm2015 as esm2015
Compiling @angular/core/testing : fesm2015 as esm2015
Compiling @angular/core : esm2015 as esm2015
Compiling @angular/animations/browser : fesm2015 as esm2015
Compiling @angular/platform-browser : fesm2015 as esm2015
Compiling @angular/common/http : fesm2015 as esm2015
Compiling @angular/common/testing : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015
Compiling @angular/platform-browser/testing : fesm2015 as esm2015
Compiling @angular/router : fesm2015 as esm2015
Compiling @angular/animations/browser/testing : fesm2015 as esm2015
Compiling @angular/common/http/testing : fesm2015 as esm2015
Compiling @angular/forms : fesm2015 as esm2015
Compiling @angular/platform-browser/animations : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : fesm2015 as esm2015
Compiling @angular/router/testing : fesm2015 as esm2015
Compiling @angular/animations/browser : esm2015 as esm2015
Compiling @angular/core : main as umd
Compiling @angular/animations/browser : main as umd
Compiling @angular/animations/browser/testing : esm2015 as esm2015
Compiling @angular/animations/browser/testing : main as umd
Compiling @angular/common : esm2015 as esm2015
Compiling @angular/common/http : esm2015 as esm2015
Compiling @angular/common : main as umd
Compiling @angular/common/http : main as umd
Compiling @angular/common/http/testing : esm2015 as esm2015
Compiling @angular/common/http/testing : main as umd
Compiling @angular/forms : esm2015 as esm2015
Compiling @angular/forms : main as umd
Compiling @angular/platform-browser : esm2015 as esm2015
Compiling @angular/platform-browser/animations : esm2015 as esm2015
Compiling @angular/platform-browser : main as umd
Compiling @angular/platform-browser/animations : main as umd
Compiling @angular/core/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic : esm2015 as esm2015
Compiling @angular/core/testing : main as umd
Compiling @angular/platform-browser-dynamic : main as umd
Compiling @angular/platform-browser/testing : esm2015 as esm2015
Compiling @angular/platform-browser/testing : main as umd
Compiling @angular/platform-browser-dynamic/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : main as umd
Compiling @angular/common/testing : esm2015 as esm2015
Compiling @angular/common/testing : main as umd
Compiling @angular/router : esm2015 as esm2015
Compiling @angular/router : main as umd
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router/testing : main as umd
```

Doesn't touch the  `angular-gridster2` library

**Comment by ahnpnl** [comment]
We need `ngcc` because it does also process all packages under `@angular`. If those packages are not processed by `ngcc`, Jest won't run correctly. If I don't run `ngcc` explicitly from terminal, the `require('jest-preset-angular/ngcc-jest-processor');` doesn't run at all which explains why tests failed.

**Comment by michaelfaith** [comment]
I can work with that.  Thanks for helping to zero in on the issue.  Adding "postinstall": "ngcc" to the top level package.json (not the lower one), it all works as expected.  Appreciate the help.
